### ISSUE TITLE
Load ERM data - import records for books, databases, and journals

### ISSUE THREAD

**Issue by mashanadavis** [NIHL/Drupal7-Migration#1]
To do this: 
(1) download all records from SQL
(2) update records with new information from Elsevier 
(3) Map column headings in the spreadsheet with those in Drupal and prepare Tampers in Drupal
(4) QA on data prior to import
(5) Import data
(6) QA on data after import

**Comment by cmndr-king** [comment]
On 11/18 Ben noted that he has been working on cleaning up the data in the ERM, finding multiple rounds of issues.  There is an issue with the subject data coming from NLM which is preventing the migration of subjects to the new taxonomy.

**Comment by cmndr-king** [comment]
James downloaded the three sheets and posted them to BaseCamp today - John will load the data while Bridget works on finding and cleaning up the NLM subject-to-journal list.

**Comment by mashanadavis** [comment]
After some discussion with John, we are going to remove the "Resource Source" content type, and turn the Publisher and Provider fields into taxonomies. 

I don't think this will have an affect on the ERM data or other content.

**Comment by mashanadavis** [comment]
The ERM data was imported on 4/4/2016. Discussions related to the ERM import are on Basecamp: 

ERM Content Import: https://basecamp.com/2765815/projects/7275781/messages/54924493

Books - questions and discussion: https://basecamp.com/2765815/projects/7275781/messages/56455602

Journals - questions and discussion: https://basecamp.com/2765815/projects/7275781/messages/56448579

Databases - questions and discussion: https://basecamp.com/2765815/projects/7275781/messages/56487066

Misc ERM questions and discussion: https://basecamp.com/2765815/projects/7275781/messages/56592697

Search: https://basecamp.com/2765815/projects/7275781/messages/56595207

Please refer to these discussions when reviewing/addressing this ticket.

**Comment by mashanadavis** [comment]
John, to our understanding the ER data is in Drupal, but some cleanup is required based on discussions with Bridget on April 14. Do you need to reimport the data? If not, then I think we can close the ticket. If new things arise with the ER data, then new tickets can be generated.

**Comment by jronmorgan** [comment]
Data has been reimported. If this looks ok the ticket can be closed as only tweaks will be made going forward.

**Comment by mashanadavis** [comment]
John, the resource title points to a Page Not Found page. Is this what's supposed to occur for the beta release? Prior to this import, the link pointed to the node.

**Comment by jronmorgan** [comment]
Hi MaShana,

I screwed up this morning... I pushed the data up but forgot to clear the Solr index..  Items are being replaced as solr processes them but must will have stale links from search until the solr updates have finished. Now, given the UI impact, I am afraid to go ahead and try to do that *now*.

I will make my final DB tweak tonight (just adding Public access taxonomy to those that either have none or are NIH), clear the index completely and then try and force an immediate, complete indexing.

The other possible issue is likely the tokenizing of the link as its displayed in the view output. I will go ahead and validate that that is actually correct.

BTW, most of my drush work was on my local server.. I really did very little on the actual stage box this morning. I think its mostly the cron updating to solr that's killing us.

-john

________________________________

**Comment by tgifford-webfirst** [comment]
For the record, example 404s for resources can be had here: http://nihlibrarystg.prod.acquia-sites.com/search/site?f[0]=im_field_resource_type%3A2

It appears Solr is seriously confused, because there are no more documents to index:
http://nihlibrarystg.prod.acquia-sites.com/admin/config/search/apachesolr

I will troubleshoot that, since we are trying to publish to prod today.

**Comment by tgifford-webfirst** [comment]
Indexing has finished. There shouldn't be any more 404s.
