### ISSUE TITLE
HOME button links back to NIH agency homepage, not the intended agency.

### ISSUE THREAD

**Issue by mashanadavis** [NIHL/Drupal7-Migration#10]

**Comment by jronmorgan** [comment]
I may have to be in the office to see this. How can I test being logged in under a given organization without actually being logged for that organization? Not being able to do so might be a big problem for administration and development as time gores on.

**Comment by mashanadavis** [comment]
Maybe when we meet on Monday you can go over this with Ben. I've tried testing in the office as well and being logged into EZProxy and the same issue occurred. I don't think the intended functionality works in the code.

**Comment by tgifford-webfirst** [comment]
One way to fix this is with an approach similar to the frontpage module:
1. Create a new menu callback to serve as the Drupal "default front page" setting.
2. In that callback, redirect the user to the appropriate agency homepage.
3. Early in the request to the correct agency homepage, set &$drupal_static_fast['is_front_page'] to TRUE.

This approach may have issues with the varnish cache, so more research is needed.

**Comment by tgifford-webfirst** [comment]
This is ready for review on stg, but the code has not been merged with master yet. The default front page setting was changed in the database, which will cause errors if different code is deployed, so devs beware.

**Comment by tgifford-webfirst** [comment]
Update: the code was merged a while back, so caveats in previous comment no longer apply, and this can be closed.
