### ISSUE TITLE
Change Font - Sitewide for readability

### ISSUE THREAD

**Issue by svpatel1** [NIHL/Drupal7-Migration#100]
We propose changing the fonts (size and family) and make the site more readable. While we will make the major theming changes, later on, when tackle the theme - we feel a good first step would be to make the site easier to access/read prior to beta launch. We propose using the fonts on the ORS website - http://www.ors.od.nih.gov/Pages/home.aspx. 
I believe the fonts used are Helvetica, & Neue. We propose using the 14px size (a little bigger than the ORS site), however, we will have to test this to ensure it doesn't cause problems. Comments are invited.

**Comment by theBrarian** [comment]
I am working with the group developing our brand style guide. Will have the useful pieces sometime in April. Google Developers site suggest 16 CSS px as a base with small being 75% and large 125% of base.

**Comment by theBrarian** [comment]
h1, h2, h3 obviously being a percentage off the base. H1 usually about 250%. Google also recommends line height of 1.2 and line height of lists at 200%.

**Comment by mashanadavis** [comment]
This a minor adjustment, but it's been in progress for a while. Are we moving forward with this?

**Comment by tgifford-webfirst** [comment]
Yes, this has been deployed as a quick fix. We will move to 16px when we re-theme.

**Comment by mashanadavis** [comment]
Yay! Closing ticket.
