### ISSUE TITLE
Make Training Pages more clear - Create Mocks

### ISSUE THREAD

**Issue by svpatel1** [NIHL/Drupal7-Migration#101]
We will create a couple of mockups of the training pages - 

http://nihlibrarystg.prod.acquia-sites.com/content/cancer-genome-atlas-tcga-data-analysis

Issue is that Registration is not obvious: 

also layout is a bit confusing (e.g. can't tell if a class is available, etc...).

Comments are welcomed.

**Comment by theBrarian** [comment]
I agree that there is not a clear Call to Action (Register). Besides CSS issues, there is lacking a hierarchy of content. There is no clear focus on page.

**Comment by mashanadavis** [comment]
Will the changes here have any bearing on the content that we're putting in?

**Comment by tgifford-webfirst** [comment]
No, the design changes won't affect your content entry. We re-organized the content on the page in the mockups, but didn't add or remove anything.

**Comment by mashanadavis** [comment]
Thanks. The ticket was moved to QA, but I don't see the changes on STG.

**Comment by tgifford-webfirst** [comment]
I thought this ticket was just for creating the mockups. Do you want to track the implementation here as well?

**Comment by svpatel1** [comment]
I believe we mosted this discussion on the design comps to base camp.. we may want to start a new ticket for actual theming/implementation of the design.

**Comment by mashanadavis** [comment]
Sorry. I just reread the ticket description. You are correct in that we need to create a ticket to for theming. Will this be a part of the over theme that's planned for Phase 2, or for this beta release?

**Comment by svpatel1** [comment]
This will be included in this months release, it is pretty straightforward. MaShana,would you like to create a new ticket for the theming of the training pages?
