### ISSUE TITLE
Create Test Plan - with Scenarios

### ISSUE THREAD

**Issue by svpatel1** [NIHL/Drupal7-Migration#102]
Working on a test plan for internal testing purposes 
- focus on personalization
- training/instruction

**Comment by theBrarian** [comment]
I can work with someone on this to create a few scenarios. Also looking a a few heuristic evaluation templates fro staff to use when testing.

**Comment by mashanadavis** [comment]
Brian - The whiteboard outside of James' office has a space dedicated to the test scenarios. It's a start for our internal team. We will work with WebFirst on this as well, if they have time. 

Another idea that goes along with this is using Morae during the testing period. Please investigate our license related to Morae. Also, let's discuss a plan of action for capturing user feedback.

**Comment by svpatel1** [comment]
MaShana, i have a rough document of some use cases (mostly around the login and authentication process), I am not yet comfortable posting it but I will send it as soon as possible.

**Comment by mashanadavis** [comment]
Great! We will work other scenarios. If you have ideas for other areas of the site feel free to add them.

**Comment by mashanadavis** [comment]
Sanjay and I met today to discuss the test plan. Given that the BR1 is only open to staff in the library, a formal test plan is not required. 

Here are the draft questions: https://basecamp.com/2765815/projects/7275781/documents/10906577.
