### ISSUE TITLE
Configure IHS region links for EZProxy

### ISSUE THREAD

**Issue by cmndr-king** [NIHL/Drupal7-Migration#105]

**Comment by cmndr-king** [comment]
James is checking with John Morgan and Ben Hope to identify the links for the IHS subpage.

**Comment by 4benhope** [comment]
Please reply into this ticket about the IHS regional links for EZProxy

**Comment by cmndr-king** [comment]
Ted needs to know how to configure EZProxy links for the regional connections within IHS. Do we simply add a /regionname?  If so, does it matter what we pick for the region name?

**Comment by jronmorgan** [comment]
We can add anything we want and EZproxy will pass it thru to use however we currently convert everything to a Customer Group taxonomy tid and it will  error on any unknowns.

**Comment by tgifford-webfirst** [comment]
I don't have full visibility on this issue, but for the record, which of the following are the goals for IHS regional links?

* Track usage by IHS region
  * In EZProxy
  * In Drupal
* Allow IHS regions to login properly or securely
* Customize content display within Drupal based on the IHS region
* Customize content access within Drupal based on the IHS region

**Comment by cmndr-king** [comment]
Official regional name abbreviations used by IHS:

    IHS Headquarters - IHS/HQ
    IHS Alaska - IHS/ALK
    IHS Albuquerque - IHS/ALB 
    IHS Bemidji - IHS/BEM
    IHS Billings - IHS/BIL
    IHS California - IHS/CAL
    IHS Great Plains - IHS/GPL
    IHS Nashville - IHS/NAS
    IHS Navajo - IHS/NAV
    IHS Oklahoma City - IHS/OKL 
    IHS Phoenix - IHS/PHX
    IHS Portland - IHS/POR
    IHS Tucson - IHS/TUC

**Comment by mashanadavis** [comment]
To confirm, these groups will not need their own agency homepage, correct? They all will use IHS’ agency homepage.

**Comment by mashanadavis** [comment]
From the status meeting April 27:

John suggested that we add the IHS regions to the Customer Group taxonomy. Attributes will cascade down. Content display and/or access will not be customized at this time, but the capability will be available for future use in case it is needed.

**Comment by jronmorgan** [comment]
Code has been updated and pushed to master to support the given IHS regions.

Notes:
- Not quite sure how/where to test it as the dev database is now very out of sync with production
- taxonomy updates where required and are complete in production
- the signing/IHS page has been updated to support there individual regions locally
  - prod has not been updated as it would break production logins without the proper code being pushed up
  - I have not made this update to the dev database as the entire login system is out of date there
- URLs sent to EZproxy have been validated as functional on the drupal side.

- Something happened and not all the Agency landing pages have URL aliases set for them. These must all be checked and added when missing.

We're basically ready to go with this as soon as the EZproxy issue is figured out.




________________________________
