### ISSUE TITLE
Media upload widget not working

### ISSUE THREAD

**Issue by mashanadavis** [NIHL/Drupal7-Migration#106]
Able to add files (image, docs, etc.) from computer, but cannot add a previously uploaded file (in My Library).

Noticed this bug when attempting to create a staff profile and add an image and also adding an image to the Agency Homepage content type. 

Bug should be fixed.

**Comment by tgifford-webfirst** [comment]
I was able to use an existing image on the ACF homepage from the "Library" tab without any issues. See http://nihlibrarystg.prod.acquia-sites.com/agency/acf.

I will try creating a new content node and a few other variations, but if you can reproduce the issue before I do, let me know.

**Comment by tgifford-webfirst** [comment]
Looks like the issue is when adding content. While adding a new agency homepage, I tried to select a Feature Image from the Library tab. No matter which image I choose, I receive a javascript alert that says: "You have not selected anything!".

Test URL: http://nihlibrarystg.prod.acquia-sites.com/node/add/features

**Comment by mashanadavis** [comment]
Yes, this is the same error I received. Adding an image from your computer works. I added three new staff profiles today and was able to add an image. It’s only when selecting an image from the library does the error appear.

**Comment by tgifford-webfirst** [comment]
This is a bug in the Media module, which is unfortunately in a state of flux after one of the maintainers passed. I will look into the various patches--we might have to go with a \-dev version of the module for the time being. Here is the bug that is affecting us:

* https://www.drupal.org/node/2534724

**Comment by tgifford-webfirst** [comment]
As a workaround, you can click the red "X" to close the duplicate popup, then choose the file from the Library. I believe this only applies when adding a new image/file, not when replacing an existing image. The most common case of this is creating a new node, but it can also happen while editing a node if an image was not uploaded or chosen when the node was created.

**Comment by tgifford-webfirst** [comment]
Well, that was a short-term workaround. I've switched the module to \-dev after reviewing the diff with \-beta1. We should be good for the time being, but please keep an eye out for any funny behavior from Media.

**Comment by mashanadavis** [comment]
Works. Closing ticket.
