### ISSUE TITLE
Agency Homepage content type has extra URL field that doesn't work

### ISSUE THREAD

**Issue by mashanadavis** [NIHL/Drupal7-Migration#108]
Updating content and found the extra field. Not sure if the duplication is causing the hyperlink to not be applied. The second URL field works. 

I suppose the extra field could be removed, but wanted to make sure it wouldn't have any affect on the content type.

**Comment by tgifford-webfirst** [comment]
The extra field (field_url_feature) doesn't have any data, so it can be deleted. However, it is part of an enabled feature module, so we will need to remove it from the code there first.

**Comment by tgifford-webfirst** [comment]
Deleted.
