### ISSUE TITLE
Agency Homepage: Alias URLs return a Access Denied message

### ISSUE THREAD

**Issue by mashanadavis** [NIHL/Drupal7-Migration#111]
I think I understand why this is happening, but want to make sure I'm correct. 

HHS users will probably bookmark their agency page (e.g. http://[base URL]/agency/acf). Do we want them to encounter an Access Denied message? Or, will this even occur? Am I missing something?

**Comment by svpatel1** [comment]
Our thought is that if they bookmark the page and  are not logged in, they will be redirected to the login page. Let us know if this is acceptable.

**Comment by mashanadavis** [comment]
Let us spend some time internally working out the workflow. We will get back to you today on this.

**Comment by mashanadavis** [comment]
After further discussion, the user should be redirected to the appropriate login page. So, move forward with this workflow.

**Comment by mashanadavis** [comment]
I'm at home today and logged in using the Remote Access link in the site and encountered a PAGE NOT FOUND error. Below is the URL I was redirected to after logging in:

http://nihlibrarystg.prod.acquia-sites.com.ezproxy.nihlibrary.nih.gov/ezpsignin/NIHhttp://nihlibrary.nih.gov

I was working on the URL patterns this week. Does that have anything to do with this error? 

All of the agency aliases follow this pattern: http://[base URL]/agency/[agency name]. If its an OS subagency, then the pattern is http://[base URL]/agency/os/[subagency name]. If this is not the correct landing/redirect page, please let me know or update the pages/redirects appropriately.

**Comment by tgifford-webfirst** [comment]
Can you provide the exact sequence of pages/URLs you visited, starting from before you clicked the remote access link?

**Comment by cmndr-king** [comment]
Try to connect when not on VPN. All morning, we have been having network firewall issues that was blocking access to many external sites. Cindy was having problems accessing AlzPED while on VPN but not off VPN.


 -James
_______________________________
James King, MLS, FSLA

Branch Chief & Information Architect
Information Resources & Services Branch
National Institutes of Health Library
Division of Library Services
Office of Research Services
Building 10, Room 1L-13G, MSC 1150
Bethesda, MD 20814<x-apple-data-detectors://3/0>
Phone: (301) 496-2187<tel:(301)%20496-2187>
Cell: (240) 421-0573<tel:(240)%20421-0573>
Fax: (301) 402-0254<tel:(301)%20402-0254>
E-mail: James.King@nih.gov<mailto:James.King@nih.gov>

Stay connected with the NIH Library:
Web: http://nihlibrary.nih.gov<http://nihlibrary.nih.gov/>
Facebook: http://www.facebook.com/nihlibrary
Twitter: http://www.twitter.com/nihlib
_______________________________
Your Partner in Research

Please consider the environment before printing this e-mail

On Apr 20, 2016, at 10:39 AM, MaShana Davis <notifications@github.com<mailto:notifications@github.com>> wrote:


I'm at home today and logged in using the Remote Access link in the site and encountered a PAGE NOT FOUND error. Below is the URL I was redirected to after logging in:

http://nihlibrarystg.prod.acquia-sites.com.ezproxy.nihlibrary.nih.gov/ezpsignin/NIHhttp://nihlibrary.nih.gov

I was working on the URL patterns this week. Does that have anything to do with this error?

All of the agency aliases follow this pattern: http://[base URL]/agency/[agency name]. If its an OS subagency, then the pattern is http://[base URL]/agency/os/[subagency name]. If this is not the correct landing/redirect page, please let me know or update the pages/redirects appropriately.

**Comment by mashanadavis** [comment]
My workflow:

1. Started here: http://nihlibrarystg.prod.acquia-sites.com/agency/nih
2. Clicked Login and select NIH Remote Access
3. Logged in using my NIH credentials
4. redirected to http://nihlibrarystg.prod.acquia-sites.com.ezproxy.nihlibrary.nih.gov/ezpsignin/NIHhttp://nihlibrary.nih.gov

which gave the error message.

**Comment by tgifford-webfirst** [comment]
The issues you're having today probably can't be fixed on the Drupal side.  It appears that the page you see in step 2 (and submit in step 3) has the correct URL in it (...%3furl%3dhttp%3a%2f%2fnihlibrarystg%2eprod%2eacquia--sites%2ecom%2fezpsignin%2fNIH -- notice that it ends with ezpsignin/NIH). So perhaps iTrust or EZProxy is configured with a whitelist of URLS? Seems odd, but I won't be able to debug it from here, so create a new ticket and assign to John.

**Comment by mashanadavis** [comment]
Bridget just tested this while on telework and received the same error message. I will submit a ticket, but what should it say? Check iTrust or EZproxy settings???

**Comment by mashanadavis** [comment]
At home, not on VPN: Entered URL as .../agency/acf and was routed to .../signin/main. This is the correct action.

At home, on VPN: Entered URL as .../agency/acf and was routed to .../agency/nih and a message appeared prompting me to Logout <hyperlinked>. When I clicked the link, I was routed to .../signin/main.

I believe this is resolved.
