### ISSUE TITLE
Agency Homepage: Upcoming Training - Display next 5 classes

### ISSUE THREAD

**Issue by mashanadavis** [NIHL/Drupal7-Migration#112]
Widget should display next 5 (or # that can fit in block) classes.

**Comment by gbohara** [comment]
Mashana, 
Just to be sure I am going in the right direction, does it mean we only need to show the training with future date?

**Comment by mashanadavis** [comment]
The View currently displays training sessions in DESC order. It should be ASC order and should display the next 4-5 classes. We have a list of upcoming training on our current homepage (SharePoint): http://nihlibrary.nih.gov/Pages/default.aspx that might help.

**Comment by gbohara** [comment]
Left as it is  to display max 4 items. It won't fit 5 items if the title of training is long enough to cover 2 lines. Also it won't display any past training.
