### ISSUE TITLE
Instruction: Training and Training Session not connected by Training Category

### ISSUE THREAD

**Issue by mashanadavis** [NIHL/Drupal7-Migration#114]
The Training Category facet on the training calendar view page doesn't filter the classes. 

Training contains Training Category (taxonomy) and Training Session doesn't. Also Training contains NIH Subject and until today, Training Session did not. 

How will the facets work? I thought that by creating the parent-child relationship the info would cascade down, but it doesn't appear to work that way.

**Comment by tgifford-webfirst** [comment]
These are not FacetAPI facets, just views exposed filters that look like facets. The views exposed filter for category (in both calendar and latest_training views) needed to be configured to filter on the parent instead of the child/session.

**Comment by mashanadavis** [comment]
Works now. Closing ticket.
