### ISSUE TITLE
Web Forms not submitting to Desk Tracker

### ISSUE THREAD

**Issue by MarcellaFredriksson** [NIHL/Drupal7-Migration#115]
I tried submitting three forms to Desk Tracker, no tickets were created. I submitted Ask a Question, Bioinformatics Consult, and Bioinformatics Registration http://nihlibrarystg.prod.acquia-sites.com/node/4
http://nihlibrarystg.prod.acquia-sites.com/node/5
http://nihlibrarystg.prod.acquia-sites.com/node/6

**Comment by tgifford-webfirst** [comment]
If this was implemented with Rules, they may be in a disabled feature.

**Comment by gbohara** [comment]
Marcella
Do you remember when it was working  the last time (if it was working)?

**Comment by MarcellaFredriksson** [comment]
It pre-dates me working on this project. I just started a few weeks ago. MaShana may know.

**Comment by mashanadavis** [comment]
Ganga, the forms were working when the website was handed over by the former developer/contractor. So, the connection may have been lost once WebFirst started working the site. Not placing blame☺. I remember Ted saying something about this at some point.

**Comment by gbohara** [comment]
Mashana
Can you provide me the url or the name of the application of Desk tracker ? Or email address (if used in anyway) for notification purpose.

**Comment by mashanadavis** [comment]
The sender would be NIH Library Help.” Is the previous form data in the code? Our current forms sit on an IIS server that we don’t have access to at the moment. I will ask the staff person(s) about this and get back if this is not enough.

Is this all you need to know or do you need to know the workflow---what happens upon submission?

**Comment by gbohara** [comment]
Workflow would be helpful as well. 
Trying to figure out whether it was in the code or not and how it was implemented.

**Comment by theBrarian** [comment]
Here is the code for the present, working forms on the site (I removed form layout and content part as that is already done. :

<head>
<meta http-equiv="Content-Type" content="text/html; charset=windows-1252">
<meta http-equiv="Content-Language" content="en-us">
<title>Ask A Question Form</title>
<script>
function validateForm() {
    var x = document.forms["aspnetForm"]["email"].value;
    var atpos = x.indexOf("@");
    var dotpos = x.lastIndexOf(".");
    if (atpos<1 || dotpos<atpos+2 || dotpos+2>=x.length) {
        alert("Not a valid e-mail address");
        return false;
    }

}
</script>
</head>

<body>
<form name="aspnetForm" onsubmit="return validateForm();" method="post" action="https://live.desktracker.com/kbase/public_form_handler.php" id="aspnetForm" target="_top">

<input type="hidden" name="library" id="library" value="271234"> 
<input type="hidden" name="bypass_confirmation" id="bypass_confirmation" value="true">
<input type="hidden" name="form_custom_email_subject" id="form_custom_email_subject" value="NIH Library - Ask a Question">
<input type="hidden" name="FormName" id="FormName" value="Ask A Question">
<input type="hidden" name="form_custom_webform_redirect" id="form_custom_webform_redirect" value="http://nihlibrary.nih.gov/Services/Pages/Thank-You.aspx">
<input type="hidden" name="IP_Address" value="<%=Request.ServerVariables("REMOTE_ADDR")%>">
<input type="hidden" name="Browser" value="<%=Request.ServerVariables("HTTP_USER_AGENT")%>">
<input type="hidden" name="username" value="<%= Request.Cookies("newuser") %>  ">
<input type="hidden" name="form_main_input_field" value="question" /> 

<style type="text/css"> 
.shh323{display:none;} 
</style>
<p class="shh323">Nothing in the following field: &nbsp; <input name="EmailAddress" id="EmailAddress" type="text" class="shh323" /></p>

<% dim spamStop1 
spamStop1 = trim(request.form("EmailAddress")) 
if spamStop1 <> "" then 
alert("Seriously?") 
end if %> 

    
      
</form>

<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-47400614-1', 'nih.gov');
  ga('send', 'pageview');

</script>
</body>

**Comment by theBrarian** [comment]
I can email the code for the form as it does not seem to like it here in comments.

**Comment by gbohara** [comment]
Marcella, Mashana
Can you test it on stg site  and let me know if it works now?

**Comment by MarcellaFredriksson** [comment]
I tested the Ask a Question form at http://nihlibrarystg.prod.acquia-sites.com/ask-question
My query submitted to Desktracker.
However, the email address recorded from the form is chintan.desai@feisystems.com
![webform-email](https://cloud.githubusercontent.com/assets/18288544/14892567/6455be36-0d39-11e6-9d96-cee5043f7fef.png)

**Comment by mashanadavis** [comment]
Chintan is one of the former developers.

**Comment by gbohara** [comment]
Can you test it again?  
The code was written to use that email address for testing purposes.  I have fixed it.

Please test couple of different webforms if possible. If everything turns out to be alright, I will move the code to production.

**Comment by MarcellaFredriksson** [comment]
I tested 3 forms -- Ask a Question, Bioinformatics, and eTrouble and all three submitted to DeskTracker with the correct data (name, email address, question, etc.)

**Comment by mashanadavis** [comment]
Hi, I tested three forms but do not see them in Desk Tracker: Editing Request, Suggest a Resource, Request a tutorial.

**Comment by gbohara** [comment]
Mashana, 
 Just for confirmation, somehow you did not use the production site. Did you?

**Comment by gbohara** [comment]
I moved the code to production. Saw these new submissions from Mashana on production. 
I think we should be fine now. The production should also work now.

**Comment by mashanadavis** [comment]
I’m sorry. I thought I was on STG. Too many windows open.

**Comment by gbohara** [comment]
No worries :).

**Comment by mashanadavis** [comment]
Closing ticket.
