### ISSUE TITLE
Determine why content is weighted higher than title in searches

### ISSUE THREAD

**Issue by tgifford-webfirst** [NIHL/Drupal7-Migration#117]
The Solr settings seem to indicate that the title should be weighted higher, but debugging the Solr query shows that the opposite is happening.

**Comment by mashanadavis** [comment]
Possibly configure search to allow single character.

**Comment by mashanadavis** [comment]
Is this ticket being focused on this week?

**Comment by tgifford-webfirst** [comment]
Please open a new ticket if you want to pursue the single character search config.

**Comment by tgifford-webfirst** [comment]
Well, it looks like this is the desired behavior, at least according the the apachesolr maintainers: https://www.drupal.org/node/2157535. There are lots of technical details about how Solr works.

What it means for this site is that we probably need to boost the title field as high as it will go, because we have a lot of Resources with very little body content, which means any match in the body gives the resource a large boost. I will increase the boost on title and we will have to see what the feedback is on the search.

**Comment by tgifford-webfirst** [comment]
In addition, only the body content receives a boost for matching phrase queries, the title does not. We could consider adding the title as a "content" field, see #118.
