### ISSUE TITLE
URL patterns based on sitemap

### ISSUE THREAD

**Issue by alwaysmashana** [NIHL/Drupal7-Migration#119]
We need to implement URL patterns for content. These patterns should follow the sitemap and breadcrumbs (are these implemented?).

We're thinking the following pattern should be implemented:

top-level/child-page/sub-child-page.

Can we get some guidance on implementing this? A discussion was opened on Basecamp: https://basecamp.com/2765815/projects/7275781/messages/56646689.

**Comment by tgifford-webfirst** [comment]
Journals, databases, and other ERM resources will need a special implementation, since they will not be added to the menu manually.

**Comment by tgifford-webfirst** [comment]
This appears to be caused by a missing title for one resource, and non-English characters in other cases: http://nihlibrary.prod.acquia-sites.com/search/site?f[0]=ss_apachesolr_glossary%3A

**Comment by mashanadavis** [comment]
Thanks. How do we set up the patterns for this?

**Comment by tgifford-webfirst** [comment]
Please review the pattern settings page, and also all the patterns generated for the main-menu items.

**Comment by alwaysmashana** [comment]
All of but one pattern is correct. Under About Us, the patterns still include the menu subheading "General Information" and "Policies and Procedures" for those pages under this subheading. Please adjust and I think we'll be set.

**Comment by gbohara** [comment]
This should be fixed.

**Comment by alwaysmashana** [comment]
No. It's fixed. Closing ticket.
