### ISSUE TITLE
Log In button behavior needs to be adjusted

### ISSUE THREAD

**Issue by mashanadavis** [NIHL/Drupal7-Migration#12]
**Issues:**
1. Click button - links you to the EZproxy page. Need to verify that this is the intended behavior.
2. Roll over button - box disappears but Select Organization options menu still displayed. Have to initiate the button again to click Log In.

**Behavior should be:**
1. Roll over - User should be able to select an option and the box should display until the user has clicked "Log In."

**Comment by jronmorgan** [comment]
Need to go over this on Monday. It seems to work properly as far as I can tell. I don't see an issue.

**Comment by mashanadavis** [comment]
Sure we can go over it because I still see the issue in FF and IE. It's weird that you are not getting the same thing. Maybe it's just me:-).

**Comment by cmndr-king** [comment]
Switch to using JavaScript to automatically direct to the page rather than having a Login button to click.

**Comment by jronmorgan** [comment]
This is being worked on along with #43

**Comment by cmndr-king** [comment]
In the 11/4 meeting, John mentioned that he and Ted suggest that we switch the Login menu to click directly to a page rather than have a drop down menu.  James approved moving forward with this more standardized approach.

**Comment by tgifford-webfirst** [comment]
The same recommendation applies to the search form in the dropdown: we should just remove the dropdown completely. If you still want to give some indication that the user can search on other sites/systems, you can have links in the dropdown that go directly to the search pages, but that may be more confusing.

**Comment by cmndr-king** [comment]
This has been completed and works.  I will close this ticket.
