### ISSUE TITLE
Search: Change search box on search results page

### ISSUE THREAD

**Issue by mashanadavis** [NIHL/Drupal7-Migration#120]
1. Remove drop down
2. Change phrasing in search box to "Search books, databases, journals, website, and more"
3. Add a link to the Online Catalog beneath the search box

**Comment by gbohara** [comment]
Mashana
Can you please provide the link to the Online Catalog?

**Comment by mashanadavis** [comment]
Hi Ganga – Here’s the link: http://nih-library.nih.gov/.

**Comment by tgifford-webfirst** [comment]
We decided to try it with the online catalog link to the right of the Search button. Please let us know if you would still prefer the link beneath the search box.

**Comment by mashanadavis** [comment]
Link placement looks fine to me. We could leave it for now and test the placement with users. 

Does anyone else have opinions on the placement?
