### ISSUE TITLE
Training: Session title reads "Register" and "Registration closed" appears on description page for upcoming sessions

### ISSUE THREAD

**Issue by mashanadavis** [NIHL/Drupal7-Migration#123]
Here's an example: http://nihlibrarystg.prod.acquia-sites.com/node/70286/register.

Also, when registration is closed the form should not appear.

**Comment by tgifford-webfirst** [comment]
It appears that session was deleted. Is there another example?

During the call, it sounded like there were other things to change on the page as well. Do you have wireframes or other documentation on how the page should look? If not, please provide a detailed list of the desired changes.

**Comment by mashanadavis** [comment]
Here's another example: http://nihlibrarystg.prod.acquia-sites.com.ezproxy.nihlibrary.nih.gov/node/69891/register

This was my workflow, logged out using IE:

Training & Events > Training Topics > 3D Printing & Modeling > "Introduction to 3D Modeling with Solidworks."

Ideally, the page would look like this: http://nihlibrary.beta.libcal.com/event/2364388. This is what we're currently using for class registration (it's called LibCal). The page title is the class title. The class description and information (date, location, time) follow. And, then the registration form whether open or waitlist appear at the bottom. If the registration is closed, same details are displayed, but the form does not appear, rather a message, "Registration has closed." 

There is a waitlist option as part of the Registration module, not sure if it's in play right now. When classes were put in, I don't believe that Marcella looked at the registration period as this option is not available until after the class is saved. If that's causing the "Registration closed" issue then we can go back in a update the classes. 

Please let me know if you need additional details.

**Comment by tgifford-webfirst** [comment]
There was a bug in some custom tpl.php code in the theme, which has now been fixed. It was trying to check the status of the registration, but the check would always return Closed, even if registration was Open.

See http://nihlibrarystg.prod.acquia-sites.com/node/70081/register for a registration that has been closed (manually by me).

If you want to have the registration settings (such as close date) populate automatically (requiring less data entry), please create another ticket. The registration_date module would help to automatically close the registration, but it is in alpha state and hasn't been updated recently: https://www.drupal.org/project/registration_date.

**Comment by MarcellaFredriksson** [comment]
The page name is still listed as "Register" instead of the Training Session title.

**Comment by mashanadavis** [comment]
And, the registration form still appears even when the session date has passed.

**Comment by tgifford-webfirst** [comment]
My understanding of the above is that you would like the following changes:

* Change the page title for the registration page (node/#/register) to the training session title (i.e. the title displayed on the node/# page).
* Automatically set the registration close date based on the date of the training session (perhaps with the alpha-quality [registration_date](https://www.drupal.org/project/registration_date) module, a rule, or custom code).
  * Alternatively, you can manually add the registration close date after creating sessions, as you mentioned above.
* Allow webinars to have an alternate registration URL that can be specified when creating or editing the session.

Did I miss anything?

**Comment by MarcellaFredriksson** [comment]
Yes, those are the three issues. For the Beta 1 release, we may just want to focus on fixing the page title for the registration pages.  The other two issues can be resolved manually for now.

**Comment by gbohara** [comment]
Created two tickets 136 and 137 for other two issues. Fixed the title for the registration page.
