### ISSUE TITLE
Remove field_customer_group from Tool, Webpage content types

### ISSUE THREAD

**Issue by mashanadavis** [NIHL/Drupal7-Migration#129]
The Tool and Webpage content types should use the field "field_agency_access." Ted identified 440 instances where the current field is being used and they all under the Webpage content type. 

Please change the fields and move the content over to field_agency_access.

Assign it to the proper release.

Another ticket will be submitted to start a discuss about how the field_agency_access field should work.

**Comment by tgifford-webfirst** [comment]
field_customer_group is part of the nihl_layout feature, so we will need to remove it there first.

**Comment by tgifford-webfirst** [comment]
field_customer_group has been migrated to field_agency_access, after which field_customer_group was deleted. The following pages need to be reviewed for their access control behavior (they are not accessible by anonymous users):

| node_id |
|-----------|
|      [1286](http://nihlibrarystg.prod.acquia-sites.com/node/1286) |
|      [1291](http://nihlibrarystg.prod.acquia-sites.com/node/1291) |
|      [1296](http://nihlibrarystg.prod.acquia-sites.com/node/1296) |
|      [1306](http://nihlibrarystg.prod.acquia-sites.com/node/1306) |

**Comment by mashanadavis** [comment]
Checked and updated. But, when I saved the nodes, I got the following error:

    Notice: Undefined index: #field_parents in field_widget_field() (line 577 of /mnt/www/html/nihlibrarystg/docroot/modules/field/field.form.inc).
    Notice: Undefined index: #field_parents in field_widget_field() (line 577 of /mnt/www/html/nihlibrarystg/docroot/modules/field/field.form.inc).

**Comment by tgifford-webfirst** [comment]
That was unrelated. A contrib module update introduced a bug: https://www.drupal.org/node/2710919.

It is now patched.

**Comment by mashanadavis** [comment]
All appears to be well with this ticket and nodes (pages) mentioned above.
