### ISSUE TITLE
Determine the use of field_agency_access field

### ISSUE THREAD

**Issue by alwaysmashana** [NIHL/Drupal7-Migration#130]
How should this field be used?

This field assigns access or visibility to customer groups. There needs to be some discussion about how this field should work beyond that and the decision(s) should be documented on Basecamp.

**Comment by tgifford-webfirst** [comment]
This is showing up in tickets like #155 and #138. We need documentation on how each content type, view, or other page should behave if the user is not assigned the customer group associated with the main content or other content listed on the page.

**Comment by mashanadavis** [comment]
Ted - What kind of write up do you suggest? Below are the use cases. Anyone feel free to fill in where I may have missed.

Use cases:

(1)   If an NIH or CMS user, the IP address should be recognized and navigating the site should be seamless. Content displayed should be specific to that customer group.

(2)   If a Public user (IP address not recognized), the user can navigate the site. Public users can view all content types. But, to access an electronic resource (clicking the title) or to register for a class (clicking the course title), the user should be prompted to login. Possibly display a message, “You are not recognized as an authorized user of the NIH Library. Please login to complete your transaction.” This can be cleaned up.

(3)   If an HHS user, the user should be prompted to login through the main sign in page.

Do we need to create a spreadsheet of each content type, view, etc. and the assigned customer groups?

**Comment by tgifford-webfirst** [comment]
I'll make the spreadsheet and upload to basecamp.

**Comment by mashanadavis** [comment]
Ted - Let me know how I can help. I wouldn't want you to spend a lot time on creating a spreadsheet with other pressing issues on your plate. If you want to get it started then I can finish it.

**Comment by tgifford-webfirst** [comment]
Yes, I will make the template for you to complete.

**Comment by svpatel1** [comment]
This ticket is related to: https://basecamp.com/2765815/projects/7275781/messages/57911017?enlarge=228016637#attachment_228016637

**Comment by alwaysmashana** [comment]
Can this ticket be closed given the updates to #110?

**Comment by svpatel1** [comment]
Yes, we think it can be closed now, because of 110. feel free to move over.
