### ISSUE TITLE
Access Denied message when registration is disabled on a training session

### ISSUE THREAD

**Issue by alwaysmashana** [NIHL/Drupal7-Migration#138]
We found a potential bug related to the registration module. When registration is disabled for training session an Access Denied message appears after the record is saved. 

To edit the record, you have to into the Content menu. Editing is not available from registration screen.

**Comment by stanleymurgolo** [comment]
Examples: EndNote Web class on June 6, 2016, or Web of Science class on April 21, 2016.

**Comment by stanleymurgolo** [comment]
Still get access denied message when trying to view any class that has passed or classes in the future that have registration disabled.

**Comment by MarcellaFredriksson** [comment]
As anonymous user on IE11, I'm getting access denied when clicking any class session link from the calendar - past classes, current, and future.  Once logged in to Drupal, can view closed and open class sessions.

**Comment by stanleymurgolo** [comment]
It was thought that it's not recognizing users location. NIH is selected for all classes, those on NIH campus should be seeing it.

**Comment by bridgetburns** [comment]
That seems to be the case. When I try to register for an upcoming class, I receive an access denied error/you must login to register for this session. Doesn't seem to recognize that I am coming in on an NIH IP. Once I log in as NIH Remote Access, I am able to see the registration page.

**Comment by mashanadavis** [comment]
NIH and CMS are supposed to be recognized by IP. This is not working apparently. Public is supposed to have the same view NIH but should not be allowed to register. When public clicks the link they should be prompted to log in.

Ted, Is there something that we're supposed to do on our end or is this an EXProxy/authentication issue?

**Comment by tgifford-webfirst** [comment]
Let me check what the site thinks your IP addresses are, and see if we just need to add a new subnet to the Customer Group term for NIH.

**Comment by tgifford-webfirst** [comment]
I added the IP subnet that you all were logging in from: 137.187.166.*

We need to identify any other subnets that should have access as "NIH" and enter them here: http://nihlibrary.prod.acquia-sites.com/taxonomy/term/231/edit?destination=admin/structure/taxonomy/customer_group

**Comment by tgifford-webfirst** [comment]
I added the IP subnet that you all were logging in from. We need to identify any other subnets that should have access as "NIH" and enter them here: http://nihlibrary.prod.acquia-sites.com/taxonomy/term/231/edit?destination=admin/structure/taxonomy/customer_group. Do you already have the subnets documented somewhere? For specifics, we can continue the discussion on basecamp.

**Comment by jronmorgan** [comment]
Just a datapoint and not sure if this is useful but here is the unique set of IP's from the NIHL taxonomies:

+------------------------+
| field_ip_address_value |
+------------------------+
| 128.231.128.169        |
| 128.231.128.170        |
| 128.231.128.171        |
| 137.187.166.*          |
| 98.233.140.219         |
+------------------------+

This is the unique set of IP's gleaned from the apache access log:

10.170.197.16
10.170.198.196
10.170.70.14
104.247.39.34
107.20.238.9
108.15.17.173
108.51.194.102
128.231.128.170
128.231.234.1
128.231.234.33
128.231.234.97
137.187.166.103 - 137's are all NIH
137.187.166.107
137.187.166.108
137.187.166.109
137.187.166.113
137.187.166.114
137.187.166.115
137.187.166.122
137.187.166.123
137.187.166.125
137.187.166.127
137.187.166.128
137.187.166.129
137.187.166.130
137.187.166.136
137.187.166.138
137.187.166.142
137.187.166.143
137.187.166.150
137.187.166.154
137.187.166.158
137.187.166.159
137.187.166.162
137.187.166.167
137.187.166.170
137.187.166.174
137.187.166.179
137.187.166.182
137.187.166.184
137.187.166.185
137.187.166.186
137.187.166.188
137.187.166.190
137.187.166.191
137.187.166.194
137.187.166.201
137.187.166.213
137.187.166.226
137.187.166.236
137.187.167.5
137.187.250.222
137.187.251.122
137.187.251.24
150.148.14.3
156.40.140.136
156.40.140.149
156.40.141.33
156.40.149.54
156.40.192.5
156.40.254.18
156.40.254.23
165.112.42.177
165.112.42.74
165.112.44.13
165.112.44.137
165.112.44.141
165.112.45.55
166.216.165.124
173.66.24.78
198.27.70.176
208.54.44.132
209.194.228.227
209.6.72.46
23.20.53.67
45.55.209.88
50.201.180.2
50.204.42.253
50.78.68.65
50.78.68.73
54.158.25.176
54.173.130.231
54.224.75.215
66.249.66.1
66.6.46.229
68.100.121.26
70.192.208.15
70.208.132.7
70.208.137.168
71.187.192.251
72.205.51.115 - John Morgan
72.209.203.38
98.169.112.229

We seem to have a lot of .156 and .165 hits coming in. Do we know those?

**Comment by mashanadavis** [comment]
Can I ask a dumb question: aren't the IPs listed in the Customer Group taxonomy? Is this what John just shared? If not, how do the CG IPs differ from John's list?

**Comment by jronmorgan** [comment]
Yes, it is a quick listing of the UNIQUE IP's in the CG taxonomy. I was in the DB and didn't feel like writing a view for it as looking them up one at a time to make sure of them was annoying..

The longer list was from the actual apache logs since Nov 4th. I could probably get counts for each if that helps. Just thought looking at that might help us find some that we should have added to the CG taxonomy.

-john


________________________________

**Comment by 4benhope** [comment]
Bridget just met with me and it is possible or likely that we never configured the IP list for all of the sites.  She will get the list from Rebecca and upload it to Basecamp.

My fear is that in a FEI meeting when I was testing IP restrictions, I thought there was an issue with IP ranges so we’ll need to see if that works with the code we’ve inherited.

-James
_______________________________
James King, MLS, FSLA
(301) 496-2187

http://about.me/cmndr_king

**Comment by bridgetburns** [comment]
I've uploaded the list of NIH and HHS IP ranges here: https://basecamp.com/2765815/projects/7275781/messages/57863337.

**Comment by tgifford-webfirst** [comment]
See comments on basecamp.

**Comment by tgifford-webfirst** [comment]
This issue is pending discussion in #130 and #110. The current status is that we have overridden the access callback for the registration page (i.e. node/%entity_object/register) with the following logic:

1. If training session is unpublished, return default access denied page.
2. If the user doesn't belong to the Customer Groups of the training session, return the default access denied page.
  1. If the user is not signed in (i.e. a "Public" user), add a message with a link to the login page.
3. If registration is enabled, show the registration form.
4. If registration is not enabled, but the node has a registration field (which should always be true for training sessions), show the registration page, but not the form.
5. Otherwise, show the default access denied page.

**Comment by mashanadavis** [comment]
Thanks Ted. (#1) If the training session is unpublished, it shouldn’t appear to the end user, correct? And, (#2) the end user should only see what is available to their customer group.

Does this make sense? Does anyone else have a different understanding?

**Comment by stanleymurgolo** [comment]
The original ticket item "Access Denied" message when registration is disabled on a training session has been fixed. Thank you. -Stan

**Comment by svpatel1** [comment]
Also, we need to add improved messaging - not just access denied. - e.g. access denied because you do not have an NIH account ,etc.

**Comment by alwaysmashana** [comment]
Stan - Where are we with this ticket?

**Comment by alwaysmashana** [comment]
Can we close this ticket even though the language needs to be improved? We can open a new ticket for the next release to focus on updating error (and other) messages.
