### ISSUE TITLE
Add instructor information to Upcoming Sessions table on Training Page

### ISSUE THREAD

**Issue by tgifford-webfirst** [NIHL/Drupal7-Migration#139]
The date and times could be condensed to a single column to make space, perhaps.

See http://nihlibrary.prod.acquia-sites.com/node/956

See https://basecamp.com/2765815/projects/7275781/messages/55983414?asset_host=1

**Comment by mashanadavis** [comment]
To the NIHL team: Who submitted this ticket? We do not currently display the instructor(s) in LibCal unless I'm missing it.

Was this a request from the instruction team leads?

**Comment by svpatel1** [comment]
Please let us know if we should investigate this further

**Comment by alwaysmashana** [comment]
This was a request from our Instruction Team. 

Condensing the date and time might work. Another solution would be to change the width of the Title column.

**Comment by stanleymurgolo** [comment]
Added Instructor column field. Works. Closing ticket.
