### ISSUE TITLE
News story duplicating between page 5 and 6 in the news section

### ISSUE THREAD

**Issue by stanleymurgolo** [NIHL/Drupal7-Migration#145]

**Comment by stanleymurgolo** [comment]
News story "publication analysis" is duplicated across pages 5 and 6 of the news section. Also accessing these news stories in IE causes the program to crash.

**Comment by svpatel1** [comment]
Stanley , thank you for providing your feedback. could you also add your version of IE that you are using or version of any browser that you are seeing specific issues. thank you

**Comment by stanleymurgolo** [comment]
Version 11 in IE, seems to work in firefox 45

**Comment by tgifford-webfirst** [comment]
The duplicate story was actually duplicated, although not identically. It is not the same node in Drupal, so this is a content entry/import bug.

Access is denied because only NIH is selected in the Customer Group field. See #130 for discussion of how Customer Group should be used.

**Comment by stanleymurgolo** [comment]
Originally it was two separate news stories of "de-stressing" and "publication analysis". I had a graphic on the main homepage linking to the "publication analysis" story. I switched out the main homepage graphic and link to another story last week (The API graphic and story). Yesterday I wanted to switch it back to the publication analysis main homepage graphic and link to that story again. But when I looked there were for some reason now 2 de-stressing stories and no publication analysis story. Then, when I went to change one of those stories back to the publication analysis story, it changed both de-stressing stories into publication analysis stories. 

Just wanted to clarify exactly what I did. Not sure if linking from the mainpage and then deleting the mainpage link had anything to do with it.

**Comment by tgifford-webfirst** [comment]
It's hard to say exactly what happened without parsing through the log files, which is probably not worth the time. Is it possible you edited the wrong story inadvertently? Seems unlikely since you would have had to do it twice based on your description above. Still, I'm tempted to wait and see if something similar happens again before investing more time.

**Comment by stanleymurgolo** [comment]
It definitely duplicated onto another news story on its own somehow. I will go ahead and delete both and reenter. If it happens again I will let you know.

**Comment by bridgetburns** [comment]
This appears to be resolved.
