### ISSUE TITLE
WYSIWYG strips table width from page

### ISSUE THREAD

**Issue by MarcellaFredriksson** [NIHL/Drupal7-Migration#148]
Tried copying and pasting a table, editing the HTML, and also creating a table using the WSYWIG-- both strip the width when the page is saved/published.  The cellpadding and cellspacing values remain in the code, but do not appear on the saved page. 

http://nihlibrary.prod.acquia-sites.com/about-us/general-information/faqs/do-i-have-submit-my-manuscript-pubmed-central

**Comment by tgifford-webfirst** [comment]
Specifying cell/column widths is often not desirable, especially when we move to a responsive theme. That being said, there may be times where it will be useful to do just that, so we should probably pursue this at a lower priority.

In the meantime, you might consider re-working any wide tables, such as in the link above, to have abbreviated text, with explanations of the abbreviations before or after the table, if necessary. For example, the column headings could be just "Method A", "Method B", etc.

**Comment by gbohara** [comment]
This should be fixed for "Extended HTML" 

However, for Filtered HTML it does not work.
Proposed solutions
1) The simple and easy solution is to always use "Extended HTML". 
Currently  only "Administrator" and  "Super User" can use this filter.  
The other roles that might need to use this filter are "Content Author" and "Approver".
There are 6 users as "content author" and 0 user as "Approver". 
Do these roles need access to "Extend HTML" filter? 

2) With some extra module and some configuration, make it work for "Filtered HTML"

Solution 1 is already in place just needs to change some permissions (if needed) for Content Author and Approver.

**Comment by tgifford-webfirst** [comment]
Note that giving untrusted users access to "Extended HTML" as it is currently implemented has security implications, as it allows them to insert malicious javascript.

**Comment by MarcellaFredriksson** [comment]
Can set table width using extended HTML.  Closing ticket.
