### ISSUE TITLE
Outage alert notifications

### ISSUE THREAD

**Issue by cmndr-king** [NIHL/Drupal7-Migration#149]
We'd like to have a way to notify people when there are planned or unplanned outages affecting our services or resources.  This can take the form on a note on the home page or a note on the universal search for resource outages.  We'd also want the ability to have the notifications appear or not appear on NIH, CMS, and HHS sites.

**Comment by tgifford-webfirst** [comment]
There are several contrib modules that will be close to what you want, but won't quite hit the mark, especially with the differences between NIH, CMS, and HHS sites. It may be possible to supplement one of the modules without altering its code directly.

Given that you have Varnish caches, the alerts also need to be retrieved by AJAX after the (possibly cached) page loads in the browser, which several of the modules support.

* https://www.drupal.org/project/user_alert
* https://www.drupal.org/project/sitewide_msg
* https://www.drupal.org/project/alerts
* https://www.drupal.org/project/bootstrap_site_alert
* https://www.drupal.org/project/site_alert

**Comment by mashanadavis** [comment]
A simple solution could be to replace one of the features on the homepage of each site. More work but a temp fix.

**Comment by gbohara** [comment]
This functionality has been added.
It is based on the Customer Group (field_agency_access).

A new content type has been created called "Alert Notice".  The customer group can be selected from drop-down when creating these alert notices.

Currently it is displayed in all the pages in the highlighted area (that is just below the navigation). We can have further discussion on where and how to display this information and create a separate ticket for that task.

Please feel free to test this for 
1) different agencies
2) editing and re-assigning agencies (single agency / multiple agencies)
3) publishing / not publishing  alert notices
4) deleting notices

**Comment by alwaysmashana** [comment]
James - You had an idea in your mind about how this should work. Can you review this functionality?

**Comment by alwaysmashana** [comment]
We may not need this given the new theme - see ad space under the hero image.

**Comment by alwaysmashana** [comment]
Functionality tested and its working on PROD. 

James - When you create the alert you have to Publish it. This content type is not automatically published. 

Closing ticket.
