### ISSUE TITLE
Migrate to nihlibrary.nihlibrary.com?

### ISSUE THREAD

**Issue by cmndr-king** [NIHL/Drupal7-Migration#150]
Could we move the Beta 2 site to nihlibrary.nihlibrary.com or a related name like beta.nihlibrary.com?  When we go to release, we will move to the nihlibrary.nih.gov site but until then, one of these would be easier for broadcasting to beta testers.

**Comment by tgifford-webfirst** [comment]
Except for any hard-coded links, it is easy to support an additional domain. It should just work if you point the DNS to the same IP.

**Comment by alwaysmashana** [comment]
John and/or Dan - Can you add this entry to the DNS and alert WebFirst and I when this is done. WebFirst may have to do some configuring on their end and also check to see if hard URLs from the old site need to be updated.

**Comment by jronmorgan** [comment]
We don't have access to edit nihlibrary DNS entries.. James does that. Once James has done that we can tweak the site easily.

-john

________________________________

**Comment by alwaysmashana** [comment]
Thanks John. I forgot about that. When James is in tomorrow I will ask him to do this.

**Comment by alwaysmashana** [comment]
The DNS was updated. Is there anything else that needs to be done on this ticket? If not, then I will close it.

**Comment by svpatel1** [comment]
We found a few hard coded links in the content, we need to take care of.. 99% of the site should be functioning properly, Will let you know when completed.

**Comment by tgifford-webfirst** [comment]
The following content has been updated to remove the domain portion of some links (i.e. nihlibrary.prod.acquia-sites.com)

* http://nihlibrary.prod.acquia-sites.com/node/141146/edit (third link)
* http://nihlibrary.prod.acquia-sites.com/node/141416/edit (banner image)
* http://nihlibrary.prod.acquia-sites.com/node/141421/edit (banner image)
* http://nihlibrary.prod.acquia-sites.com/node/25/edit (quick links and features)

The following content still needs to be updated. It uses a moderated workflow--would you like us to update the content and re-publish it?

* http://nihlibrary.prod.acquia-sites.com/node/69886
* http://nihlibrary.prod.acquia-sites.com/node/69896
* http://nihlibrary.prod.acquia-sites.com/node/70091
* http://nihlibrary.prod.acquia-sites.com/node/70096

**Comment by jronmorgan** [comment]
I don't think so..  the sites seem fully accessible.

-john

________________________________

**Comment by alwaysmashana** [comment]
Hi Ted – Yes, please update and re-publish the content. Thanks!

**Comment by tgifford-webfirst** [comment]
The trainings have been updated.
