### ISSUE TITLE
Login - troubleshoot library provided accounts

### ISSUE THREAD

**Issue by cmndr-king** [NIHL/Drupal7-Migration#151]
When connecting to non-NIH groups, doesn't seem to redirect properly when on NIH network.

**Comment by jronmorgan** [comment]
There seems to be a problem with using a drupal static for is_public user when the value needs to be session and not page based (the first thing done on login is to redirect to another page and the  is_public check then fails on the subsequent page)

**Comment by tgifford-webfirst** [comment]
For truly public users, (i.e. not "signed-in" via ezproxy, and not recognized by IP address), we don't want to start a session. That allows the Varnish caches to work for that class of users.

Do you have a network trace or firebug/devtools export?

**Comment by jronmorgan** [comment]
Ted, per our conversation, the issue I was having is not directly *this* issue, however yes, the basic IP check does seem to work. I have a suspicion that it may be with either the IP data that we have in the taxonomies or that somehow we aren't clearing the session and resetting it properly when the user changes groups.  I will go in to NIH tomorrow or work with Bridget on remote to trace thru the issue on-network.

**Comment by bridgetburns** [comment]
The linking works as it should in the log in table page. The issue is with the drop down links. They go only to iTrust with no way for the user to get to a log in screen for a library provided account. IMO, it's  confusing to have both the table view and the drop down options, especially because it is not so obvious to get to the log in table page.

**Comment by alwaysmashana** [comment]
Bridget's suggestion was to make the Log In mega menu a button. Basically, remove the drop down and direct users to the main sign in page.

**Comment by gbohara** [comment]
The login dropdown items have been removed.
