### ISSUE TITLE
Posts by date needs to be corrected

### ISSUE THREAD

**Issue by stanleymurgolo** [NIHL/Drupal7-Migration#153]
The posts by date in the news section should be sorting stories by the date of the news story not the date entered. Also getting an "access denied" trying to view the API news story.

**Comment by bridgetburns** [comment]
Me too re: the API news story (All About APIS) 
Page not found
The requested page "/node/140891" could not be found.

**Comment by tgifford-webfirst** [comment]
I will open a new ticket for the access issues, which are related to the selected Customer Group.

**Comment by tgifford-webfirst** [comment]
See #155
