### ISSUE TITLE
Access denied for news stories when accessed from NIH

### ISSUE THREAD

**Issue by tgifford-webfirst** [NIHL/Drupal7-Migration#155]
See tickets #138 and #153.

Specific URL: http://nihlibrary.prod.acquia-sites.com/about-us/news/all-about-apis-access-practical-uses-be-held-may-23

Should stories be hidden on the [news page listing](http://nihlibrary.prod.acquia-sites.com/about-us/news) and other similar listings if the user can not read them?

**Comment by tgifford-webfirst** [comment]
With the IPs being entered for NIH, I think this is ready to test.

**Comment by mashanadavis** [comment]
Works. Closing ticket.
