### ISSUE TITLE
WYSIWYG strips anchor links from page

### ISSUE THREAD

**Issue by MarcellaFredriksson** [NIHL/Drupal7-Migration#158]
Can't create an anchor link using link tool on WYSIWYG. Can't add anchor link to HTML.

**Comment by tgifford-webfirst** [comment]
Added on prod and stg. Please note that, in order to simplify markup, it is better to add an id attribute to a heading. The WYSIWYG editor does not support the header id attribute via button, so you have to add it via source, but it will not be stripped out once you add it.
