### ISSUE TITLE
Staff Directory list should be sorted by Last Name

### ISSUE THREAD

**Issue by gbohara** [NIHL/Drupal7-Migration#161]
http://nihlibrary.prod.acquia-sites.com/about-us/staff-directory

Currently it is sorted by Full Name (first + last)

**Comment by gbohara** [comment]
Need to separate the full name to First + Last name. I looked at all the name and did not find any middle names. 
Do you need to consider middle names and put extra field for it?  
If not, I can go ahead and make changes. Also, currently the "Name" is actually the title of the node. Once, two fields for first and last name are added. This title field will be disabled, so that we do not need to enter the name multiple times.

**Comment by theBrarian** [comment]
We have a detail page for each staff person. Will doing away with the Title field effect how that detail page will render?  Not sure, but the Title field might need to stay for that reason.

**Comment by gbohara** [comment]
The title field is still there. It gets automatically generated from first and last name. It should not effect detail page and any other pages where title is used. Its just for convenience for entering / editing staff profile so that we won't have to enter data twice( Also when entering twice, there is a little chance of making mistakes (Title not being same as first + last name)

**Comment by theBrarian** [comment]
Thanks for the clarification. Auto generation will definitely help with user generated errors.

**Comment by MarcellaFredriksson** [comment]
Confirming staff directory is sorted by last name. Closing ticket.
