### ISSUE TITLE
Sort Purpose dropdown menu in ascending alphabetical order.

### ISSUE THREAD

**Issue by gbohara** [NIHL/Drupal7-Migration#163]
http://nihlibrarystg.prod.acquia-sites.com/services/requests/ask-question
(Webform)

Currently, it orders in the descending order.

**Comment by alwaysmashana** [comment]
Should sort in ascending order.

**Comment by gbohara** [comment]
This is already fixed in production. I will go ahead and fix in staging.

**Comment by alwaysmashana** [comment]
My apologies. Looking at the wrong environment (STG).
