### ISSUE TITLE
Remote Access link in subfooter has wrong URL.

### ISSUE THREAD

**Issue by gbohara** [NIHL/Drupal7-Migration#168]

**Comment by MarcellaFredriksson** [comment]
LInk is http://nihlibrarystg.prod.acquia-sites.com/signin/NIH.  Got a page not found error when clicked it. Not authenticated, located off site (teleworking)

**Comment by gbohara** [comment]
Marcella, 
I forgot to mention that the staging site is not yet up-to-date. John was working on something that prevented us from updating the staging site. Can you go ahead and test the live site?  
http://nihlibrary.prod.acquia-sites.com/signin/NIH

Once John finishes his task on the staging site, we will update the staging site as well. 
I will email John about the status.
Thanks

**Comment by MarcellaFredriksson** [comment]
Link works in live site
