### ISSUE TITLE
Clicking the author should take to the list of articles created by Author instead of Author Profile page.

### ISSUE THREAD

**Issue by gbohara** [NIHL/Drupal7-Migration#169]
http://nihlibrary.prod.acquia-sites.com/about-us/news

**Comment by gbohara** [comment]
Mashana,
Can we go forward with this?

**Comment by mashanadavis** [comment]
This is a duplicate ticket of #176. Ganga and I spoke today and decided to hold off on this ticket for now. The author's name can continue to point to the staff profile.

**Comment by alwaysmashana** [comment]
I'm going to merge this ticket with #176 and close this one.
