### ISSUE TITLE
Instruction: From the Training & Events menu, clicked on EndNote Web and received an Access Denied error

### ISSUE THREAD

**Issue by mashanadavis** [NIHL/Drupal7-Migration#17]
Not logged in, but can access when logged in as Admin.

Use this URL: http://nihlibrarystg.prod.acquia-sites.com/node/541

**Comment by jronmorgan** [comment]
duplicate of #21 I believe.

**Comment by mashanadavis** [comment]
Yes it could be counted as a duplicate. When you click on training classes from different areas on the site, you may run into an Access Denied.

**Comment by jronmorgan** [comment]
I believe that the function nihl_erm_node_access() is returning a DENY when accessing this page. Trying to determine the proper test to allow access without breaking other access rules.

file: sites/default/modules/custom/nihl_erm/nihl_erm.module

**Comment by jronmorgan** [comment]
ok, this should be fixed however you must remember to select Public under Customer Group.

**Comment by mashanadavis** [comment]
Worked after updating the Training to Customer Group = Public. We may need to update the error message when content is not available to the public. Maybe requesting the visitor to log in and pointing them to the URL to do so.
