### ISSUE TITLE
Missing Apply Button From Training session listing page

### ISSUE THREAD

**Issue by svpatel1** [NIHL/Drupal7-Migration#171]
This may not be necessary. The filter works without an apply (page refreshes on the fly after you select a filter). We should have a broader discussion about whether apply buttons are always necessary.

http://nihlibrary.prod.acquia-sites.com/training/calendar

Calendar/List view - Missing “Apply” button to choose refinements (should be a blue button like other sections and Reset button is gray right now).

**Comment by theBrarian** [comment]
One of the annoying usability issues of filters is the inability to apply multiple filters at once. Especially on shopping sites. When they are completed on the fly, a user is forced to wait for the new rendering before applying additional filters.

**Comment by svpatel1** [comment]
I can see how this can get annoying, and we are happy to make this change. However,  Amazon does their filters in this same way (search 'shoes' from their main amazon search and then click the filters on the left side). Please just let us know a final decision on whether you want to make this change  - to add an apply button (and no longer refresh dynamically).

**Comment by theBrarian** [comment]
They are one of the main culprits. Amazon does not do everything right. Say I want to look for sneakers,  but just Reebok, Adidas, and Under Armor. I need to filter each one by itself before i can look at the whole set. But I will discuss with the team what they want to do.

**Comment by svpatel1** [comment]
Thanks Brian - this is a Dup of item #26 in the spreadsheet.

**Comment by svpatel1** [comment]
Any decision made on this ticket? Thank you.

**Comment by alwaysmashana** [comment]
Add an apply button.

**Comment by stanleymurgolo** [comment]
Apply button has been added and works. closing ticket
