### ISSUE TITLE
Online Catalog - link opens new tab. Should stay in same tab for analytics.

### ISSUE THREAD

**Issue by svpatel1** [NIHL/Drupal7-Migration#173]
Ticket # 53 in the feedback spreadsheet:
Please provide specific instructions on how to recreate. Links on the (http://nih-library.nih.gov/) site seem to open in same tab for us. Also, online catalog is a separate site - http://nih-library.nih.gov/....

**Comment by theBrarian** [comment]
Regarding #76 on spreadsheet. When theme and template are created, we will replace the existing banner at the catalog site ((http://nih-library.nih.gov/) .  This is more related to Ticket #179 and improved landing pages for global navigation default pages.

**Comment by theBrarian** [comment]
Regarding #53 on spreadsheet. I can no longer recreate the link that opened in new tab. All catalog links seem to open in same tab. Will close ticket.
