### ISSUE TITLE
Remove Pipe from News Page / Move author up

### ISSUE THREAD

**Issue by svpatel1** [NIHL/Drupal7-Migration#174]
http://nihlibrary.prod.acquia-sites.com/about-us/News

**Comment by stanleymurgolo** [comment]
I assumed the pipe was there to separate the date from the author, but the author is on the next line. I would suggest either moving the author up or getting rid of the vertical line "pipe".

**Comment by gbohara** [comment]
I think it looks better when moving author up and separate with " | ". Let me know if you want it completely removed.

**Comment by stanleymurgolo** [comment]
This looks nice, thank you.
