### ISSUE TITLE
Initiates Complete Different Search Page

### ISSUE THREAD

**Issue by svpatel1** [NIHL/Drupal7-Migration#178]
Item # 71 from the spreadsheet. Please provide  more detail. Does this subject list need to match the list of facets on the News page?

**Comment by theBrarian** [comment]
Here is the url for one example: http://nihlibrary.prod.acquia-sites.com/nih-subject/bioinformatics. Here is another for tags: http://nihlibrary.prod.acquia-sites.com/tags/partek

These examples seem to jump out of the architecture. They also seem to be, the subjects, a different list than what is found for the Resources section. As a user my assumption is that if I click the subject here, that I may get everything related to Bioinformatics. But this list is just for this section, as is the tags. It does not seem to be talking to other parts of the site like training or resources.

**Comment by gbohara** [comment]
I believe this came from the "NIH Subject" and "Tagged" section of various content types. 
(eg.  at the bottom of this page: http://nihlibrary.prod.acquia-sites.com/about-us/news/omiccircos-data-visualization-data-integration-april-21) 
These should be either
1) Hidden, or
2) remove link  ie. display only text , or  
3) Linked to these pages  (for example link given above)
     http://nihlibrary.prod.acquia-sites.com/categories/7
     http://nihlibrary.prod.acquia-sites.com/categories/556

News just one content type that uses those fields "NIH Subject" and "Tagged".
The other content types are:
1) NIH Subject:
 Guide, Staff Profile, News, Webpage, Resource, FAQ, Tool, Workspace, Online Tutorial, Training Session, Image, Audio, Document
2) Tagged: 
Guide, Staff Profile, News, FAQ, Tool, Workspace, Online Tutorial

Decision needs to be made on what to do with each content type (hide, remove link or link to categories page)

**Comment by mashanadavis** [comment]
Hi Ganga - Let us review this. We want NIH Subjects and Tags on each content type. NIH Subject is our high-level taxonomy and Tags is our free-form folksonomy. It will be semi-controlled. So, we will need to update the content types to reflect this. If a content is labeled with both a NIH Subject and/or Tags, when clicked either should take you to content that is labeled with that taxonomy term. 

We will also decide on the display options for each content type. Each one may not need to show both the NIH Subject and/or Tags.

**Comment by mashanadavis** [comment]
Ganga and I spoke on June 10. Outcomes: when a taxonomy term (NIH Subject or Tags) is clicked the user will be directed to the search results page.

**Comment by gbohara** [comment]
For "NIH Subject" (since it is a facet) we can link to the search results page such as 
http://nihlibrary.prod.acquia-sites.com/search/site?f%5B%5D=sm_field_nih_subject%3Ataxonomy_term%3A7.

However, it is not applicable to Tags (since it is not a facet). 
There are two ways I can think of linking "tags" to search results page
1) Just search the site for the tag  (example  tag: 3d printing)
    ie.  http://nihlibrary.prod.acquia-sites.com/search/site/3d printing
2) Create facet for "tags" and link to the search results page (similar to "NIH Subject" )
 If needed, this new facet block can be hidden.

**Comment by gbohara** [comment]
Went with the 2nd option after talking to Ted. The tags facet block is hidden currently.

Ted brought a very good point that for the news pages (http://nihlibrary.prod.acquia-sites.com/about-us/news/ethical-writing-issues-scientific-publication-class-be-held-may-4), it makes more sense to link to the categories pages(http://nihlibrary.prod.acquia-sites.com/categories/406) rather than search results.

**Comment by alwaysmashana** [comment]
After some discussion, we decided on the following:

When a user clicks on a term from anywhere in the site, they should be directed to the Search Results page with the desired content type (where they originated from) selected. For example, a user in News reading a story on Zika, clicks the Zika tag and is directed to the Search Results page. The content type News is selected and other news stories are displayed pertaining that tag. Other content types are also displayed in the facets as having the Zika tag. 

Categories in News should continue to display stories with that particular topic. However, some work needs to be done with Categories as it displays the wrong taxonomy terms. We would like to display Tags and NIH Subjects. Remove Customer Groups and any other taxonomy.

I can create a new ticket for the latter request if that helps.

**Comment by gbohara** [comment]
Created new ticket #202 for removing customer groups and other taxonomy from News pages.
