### ISSUE TITLE
Instruction: Training & Events page doesn't show the calendar or list view

### ISSUE THREAD

**Issue by mashanadavis** [NIHL/Drupal7-Migration#18]

**Comment by jronmorgan** [comment]
Need more information. The calendar should appear here as well as on the Training Calendar page? Should list view items be shown in the same table that is currently on the main Training page or in their own table?

**Comment by cmndr-king** [comment]
Looks like it is working

**Comment by mashanadavis** [comment]
The mega menu link "Training & Events" now displays the calendar by default. However, the options on the Subjects facet is not displaying. Will close this ticket and open a new ticket for this issue.
