### ISSUE TITLE
Breadcrumbs path disappears when on complete story pages / Remove current page title from breadcrumb.

### ISSUE THREAD

**Issue by svpatel1** [NIHL/Drupal7-Migration#180]
We believe this is fixed  (now news article title is showing up in the breadcrumb) however,
How should we handle breadcrumbs on story pages (e.g. http://nihlibrary.prod.acquia-sites.com/about-us/news/ngs-data-analysis-and-integration-microarray-data-partek-flow). when the title of an article is long, it goes into the right column.  options: remove the news title from the breadcrumb or shorten the title and use an ellipsis.

**Comment by theBrarian** [comment]
News titles should be removed from Breadcrumb. User does not need to navigate to the page they are presently on, nor need the breadcrumb for orientation for the present page. Breadcrumbs are navigation and orientation tool and should demonstrate how the present page fits in the architecture hierarchy.

**Comment by mashanadavis** [comment]
I agree with Brian that the title should be dropped. This is the case on the NIH main website, see this example story here: https://www.nih.gov/news-events/news-releases/prevention-may-be-essential-reducing-racial-disparities-stroke. The story title is dropped from the breadcrumb: Home > News & Events > News Releases.

**Comment by gbohara** [comment]
The current page title has been removed from the breadcrumb.
This is applied to the whole site (not only news)

**Comment by MarcellaFredriksson** [comment]
Confirming that page title removed from breadcrumb. Closing ticket.
