### ISSUE TITLE
Includes link text that is not hyperlinked before the description....

### ISSUE THREAD

**Issue by svpatel1** [NIHL/Drupal7-Migration#181]
Item #73 - please provide more detail, we are unable to find with link to page.

Includes link text that is not hyperlinked before the description. Distracting. Includes the word “Resource” in the snippet in blue text, but it is not a link.

**Comment by theBrarian** [comment]
Once user clicks "All Online Databases" from dropdown, they are taken to a search results page.  For each result on the search results page, they first see the title, which is a hyperlink. The next line includes the down arrow (not needed) and the Content Type. This text is blue and hints that it should be a link, but it is not a link. The next line states it is a database and then presents a url. This url is not a hyperlink.  Finally the last line is a hyperlink that takes to some more detailed information about the resource itself. The long hyperlink version for the link should be something more simple like "more information".
The overall snippet needs to be cleaned up for what it presents.

**Comment by gbohara** [comment]
Can we assume this needs further discussion at this point?  
Or can we just 
 1) remove the arrow, 
 2) Change color of non-link text to default site text color and
 3) Use "More Information" as link text instead of the whole URL.
 
It seems it has to do with the layout of search results as a whole.

**Comment by svpatel1** [comment]
http://nihlibrary.prod.acquia-sites.com/search/site?f[0]=im_field_resource_type%3A2

**Comment by svpatel1** [comment]
This issue is across multiple search results pages .. not just this one. We should hold off on color changes until the redesign happens. The Arrow is a quick fix and we will remove this. Comments above are helpful and we will track them for the design refresh/retheming.

**Comment by mashanadavis** [comment]
Spoke to Ganga today and we decided to:
1. Remove arrow next to content type. Change text color and put text in brackets.
2. Replace URL with "More information."

We will work with the designer later on layout/format.

**Comment by alwaysmashana** [comment]
Resolved. Closing ticket.
