### ISSUE TITLE
Home Page - Login or Remote User Login

### ISSUE THREAD

**Issue by svpatel1** [NIHL/Drupal7-Migration#182]
Ticket #77 - We request a decision on whether you want to change Login to Remote login on the main nav drop down.

"login" or "signin" is pretty standard language. Our thought is that "remote login" will be confusing - that implies that as a user I  have to use a VPN in order to login, but that is not necssarily true if you are on the NIH network, for example.  If  a public user clicks around the site, they will pretty quickly learn what they have access to. With proper messaging we can alert them to areas in which they dont have access to. Happy to make the change if that is the consensus.

**Comment by mashanadavis** [comment]
Ticket #77 refers to "Clear" and "Reset" buttons on facets, not login.
I agree that "Log In" is standard and the button label should remain as such. There was some talk about changing the label once a person is logged in/authenticated, possibly to read "Logout."

This ticket appears to be a non-issue and should be closed.

**Comment by mashanadavis** [comment]
Refer to ticket #185. Closing ticket.
