### ISSUE TITLE
IE Errors on website (shockwave)??

### ISSUE THREAD

**Issue by svpatel1** [NIHL/Drupal7-Migration#183]
I am getting an error when I try to view the website using IE. It’s trying to bring up Adobe shockwave on certain pages and it causes IE to crash. I don’t know if others are having this problem. I could probably disable shockwave but I don’t know why it’s calling it up.

**Comment by svpatel1** [comment]
Please provide version of IE. In ie 11.0.9600 not seeing any issues. Please demonstrate or help us recreate. May be happening for internal NIH locked down IE.

**Comment by stanleymurgolo** [comment]
![internetexplorerversion](https://cloud.githubusercontent.com/assets/18332467/15786675/f07c1928-298b-11e6-9a4a-41a8fbf20df7.jpg)
Hi Sanjay, the error occurs when you try to access a news article page, I assume due to the graphic? I thought it happened on other pages too but cannot recall which ones.

**Comment by svpatel1** [comment]
We are unable to recreate this error - we opened multiple new articles and all appear fine. Is this a problem for all internal NIH users of IE? Perhaps we could do a screen share and see what you are seeing.

**Comment by mashanadavis** [comment]
Sanjay - This could be an issue at NIH. I tried to review the site in IE and was able to access everything, except a news story. IE completely shutdown when I clicked one of the features or from the News box on the homepage.

**Comment by svpatel1** [comment]
thank you, we'll have to take a further look at this  using an internal browser.

**Comment by svpatel1** [comment]
MaShana, could you paste an example link of one of the news pages that are not working?

**Comment by mashanadavis** [comment]
After error URL: res://ieframe.dll/acr_depnx_error.htm#acquia-sites.com,http://nihlibrary.prod.acquia-sites.com/about-us/news/all-about-apis-access-practical-uses-be-held-may-23

![ticket-183-error-screen-capture-20160610](https://cloud.githubusercontent.com/assets/13887931/15976240/7c7c7510-2f1f-11e6-9dd4-ef12ff26dc23.PNG)

**Comment by gbohara** [comment]
For debugging purpose, I have turned of the Twitter news feed.
Can you please open the news pages in IE and see if this problem is still there?

**Comment by mashanadavis** [comment]
On DEV, STG, or PROD?

**Comment by gbohara** [comment]
production

**Comment by mashanadavis** [comment]
Same error. I tried clicking on a feature and a story from the blue boxes. Do you think it's an NIH issue? Possibly something wrong with our version of IE? Are we missing something...an update?

**Comment by gbohara** [comment]
What blue boxes are you referring to?  

It might be because of some add-on for Internet Explorer / Might be because of some CSS styles. I am trying to find it.

**Comment by mashanadavis** [comment]
From the homepage. The three blue content boxes in the middle of the page (Quick Links, Upcoming Training, News).

**Comment by gbohara** [comment]
http://nihlibrarystg.prod.acquia-sites.com/about-us/news/protein-lounge-training-offered-july-8

http://nihlibrarystg.prod.acquia-sites.com/about-us/news/all-about-apis-access-practical-uses-be-held-may-23

Mashana, can you try testing for the links above separately? (Do not open both links at once). Its on staging site

**Comment by stanleymurgolo** [comment]
I am still getting the error.

**Comment by gbohara** [comment]
Mashana, Stanley
Can you please test it again (Production site)?  I have disabled the "share this" widget this time.

**Comment by stanleymurgolo** [comment]
It works now.

**Comment by gbohara** [comment]
http://nihlibrarystg.prod.acquia-sites.com/about-us/news/ethical-writing-issues-scientific-publication-class-be-held-may-4
Please test this URL (staging site) and see if it works. "Share this" widget has been enabled.

**Comment by stanleymurgolo** [comment]
This does not work.

**Comment by alwaysmashana** [comment]
I think there is something on our end that is causing the issue. Thoughts?

**Comment by MarcellaFredriksson** [comment]
I have clicked around on PROD and STG on multiple news stories in IE 11 and can’t reproduce the issue on my machine.

**Comment by stanleymurgolo** [comment]
It worked fine when the share this widget was disabled

**Comment by gbohara** [comment]
This is the problem with IE in combination with Sharethis widget. 
The version of jquery / some code within the module (sharethis) is possibly interfering with IE settings (may be IE add-ons, may be Security settings)

**Comment by alwaysmashana** [comment]
Thanks Ganga. Is the plan to change to the ShareThis widget?

**Comment by gbohara** [comment]
The javascript that is pulled from sharethis service is causing this problem. 
Commented the code and tested on Brian's browser on 06/17 and the page just works fine.

Also turning on the ActiveX in IE temporarily fixed this problem.
http://helpdeskgeek.com/help-desk/fix-flash-crashes-internet-explorer-11/

The best thing that can be done is replace this module with alternative modules (AddThis or ServiceLinks). However,  both of the alternative modules does not provide all the social links provided by Sharethis (eg. Pinterest). 
What social links are absolutely necessary for these news?

**Comment by alwaysmashana** [comment]
Hello there - Can you add the alternative widgets/services to the ticket? We would like to discuss them today.

**Comment by gbohara** [comment]
Drupal Module
https://www.drupal.org/project/service_links

http://servicelinks.altervista.org/?q=sample 
(Click on General tab for available services ) 
For additional services, http://servicelinks.altervista.org/?q=service

**Comment by alwaysmashana** [comment]
The widgets seem a bit outdated as they do not contain popular social media platforms like IG or Pinterest. NIH.gov has a widget on their website. I will ask the developers what was used.

**Comment by alwaysmashana** [comment]
What about using Addthis https://www.addthis.com/?

**Comment by gbohara** [comment]
Thanks for pointing to this module. I did not look further into this since it is in alpha release. I will quickly look what it provides.

**Comment by gbohara** [comment]
Share this module has been disabled and New Addthis module has been added and configured for News. 
Please test on Internet Explorer.

**Comment by theBrarian** [comment]
IE is working for me. I think it looks good. I clicked each and every type from multiple places.

**Comment by alwaysmashana** [comment]
It works for me as well. 

Follow up on my conversation with the NIH.gov folks: They are using custom code, not a widget. Here's the code:

<script type="text/javascript">
var addthis_config =
{
   ui_508_compliant: true
}
</script>
<div class="addthis_toolbox addthis_default_style addthis_20x20_style">
<a class="addthis_button_print"></a>
<a class="addthis_button_email"></a>
<a class="addthis_button_facebook"></a>
<a class="addthis_button_twitter"></a>
<a class="addthis_button_google_plusone" g:plusone:size="medium"></a>
</div>
<script type="text/javascript" src="https://s7.addthis.com/js/300/addthis_widget.js#pubid=ra-515ee0a652a83852"></script>

Also, further details from another developer on the team:

"We are using AddThis javascript library. Richard has posted the code.  However, in order to make it work, it must be integrated with Drupal. There are many ways to do that.  For example, there is an AddThis module: https://www.drupal.org/project/addthishttps://www.drupal.org/project/addthis

We did not use this module.  We applied own customized approach because we only want to use ShareThis on certain content types."

**Comment by gbohara** [comment]
This module is configurable to use in any content type as needed and does not automatically apply for all content types. 
Also, the social links are configurable based on content type / display.  It also can be used in views.

**Comment by alwaysmashana** [comment]
Sounds like a winner. Let’s deem this as closed.
