### ISSUE TITLE
Spam Blocking

### ISSUE THREAD

**Issue by svpatel1** [NIHL/Drupal7-Migration#184]
Please provide which pages you would like us to install spam blocking. All forms? Also, would you like us to use a captcha - any preferences?

**Comment by theBrarian** [comment]
yes for form pages. Google ReCaptcha v.2 is the closest to 508 compliance.

**Comment by gbohara** [comment]
Installed re-captcha module and configured for all the webforms + request new password form.

Does it need to be in login form as well?  I do not see captcha in most of the login forms
http://nihlibrary.prod.acquia-sites.com/user/

Also, mollom module had already been installed and configured for determining potential span / profanity filter

**Comment by gbohara** [comment]
The wording displayed just above the captcha can be easily changed. Please let us know what wording do you want put it there.

**Comment by mashanadavis** [comment]
Brian - Can you respond to this, please? Thanks.

**Comment by theBrarian** [comment]
Hi Guys. No text above the Captcha is needed. Seems to be pretty common to just remove.  Also, with the reCaptcha v2, we don't need the spam (Mollum) on the forms. That can be removed.

**Comment by gbohara** [comment]
Mollom Privacy content and text above captcha has been removed

**Comment by theBrarian** [comment]
Work has been completed.
