### ISSUE TITLE
Log In button should change to Log Out when user is authenticated

### ISSUE THREAD

**Issue by svpatel1** [NIHL/Drupal7-Migration#185]
Log In button should change to Log Out when user is authenticated.

**Comment by MarcellaFredriksson** [comment]
I'm teleworking today. I logged in using NIH Remote Access. The Log In menu item still reads "Log In"

**Comment by MarcellaFredriksson** [comment]
Logged in as NIH Remote User while offsite (teleworking). Log in button reads "Log In". Tried refreshing the page, no change.

**Comment by gbohara** [comment]
Marcella,
Can you try this on live site as well?  or did you already try on live site?

**Comment by MarcellaFredriksson** [comment]
Sorry! I was using the wrong URL. On http://nihlibrary.prod.acquia-sites.com/agency/nih the button reads "Sign out" not "log out"

**Comment by gbohara** [comment]
"Sign out" has been changed to "Log out"

**Comment by alwaysmashana** [comment]
On PROD it still reads Sign Out.

**Comment by gbohara** [comment]
This has been addressed and now it reads "Log Out".
