### ISSUE TITLE
Training: Setting a location does not hold

### ISSUE THREAD

**Issue by stanleymurgolo** [NIHL/Drupal7-Migration#187]
When you set a training location, if you go back in to make a correction the location setting needs to be reselected instead of it holding what you have selected.

**Comment by gbohara** [comment]
It seems to be not holding when selecting  "Other Location".
 For the rest, it seems like it is working.
Can you confirm/comment on this Stanley?

**Comment by stanleymurgolo** [comment]
Yes it seems like it is just Other Location that doesn't hold.

**Comment by gbohara** [comment]
Please test this again. This should be fixed.

**Comment by stanleymurgolo** [comment]
Yes it works now. Thank you!
