### ISSUE TITLE
Training: Add Webinar as location

### ISSUE THREAD

**Issue by stanleymurgolo** [NIHL/Drupal7-Migration#189]

**Comment by gbohara** [comment]
There is already workaround in place.
There is an option on the list to select "Other Location" which opens up text box for entering custom location. This can be used to enter webinar or any other location.

Can we use the workaround mentioned above? or do we really need to add "Webinar" as location?

**Comment by stanleymurgolo** [comment]
MaShana, what are your thoughts? We have a lot of webinars and a location needs to be specified. Not sure what it is going to look like yet with the new training page layouts (webinar only), (hybrid - on location and webinar)

**Comment by mashanadavis** [comment]
The training method includes "webinar." So can the location be named "online?" 

Brian's workaround makes sense but we do have a lot of webinars and will probably add many more. So we should have a designation for this location.

**Comment by stanleymurgolo** [comment]
This sounds good MaShana. Add "Online" to the Location list.

**Comment by gbohara** [comment]
"Online" has been added to the location list on all dev, stg and prod sites.

**Comment by alwaysmashana** [comment]
New location added. Closing ticket.
