### ISSUE TITLE
Instruction: On Training & Events, facets overlapping the introductory text

### ISSUE THREAD

**Issue by mashanadavis** [NIHL/Drupal7-Migration#19]
This was reported on the first round of feedback to FEI. Never fixed.

**Comment by mashanadavis** [comment]
http://nihlibrarystg.prod.acquia-sites.com/node/161

**Comment by jronmorgan** [comment]
I don't see an issue. I tried the given link on Safari, FF and Chrome and did not see any issues. Could you attach a screen capture?
