### ISSUE TITLE
Training: BTRIS Training format needed

### ISSUE THREAD

**Issue by stanleymurgolo** [NIHL/Drupal7-Migration#190]
We need a BTRIS check box setup under Training format exactly like it was done for Webinar. So that when selected it will bring up BTRIS Registration URL with Title and URL fields. The red header can say "BTRIS Class Registration"

**Comment by stanleymurgolo** [comment]
Thinking more about it instead of "BTRIS Class Registration" it should just be "External Registration". We may have other classes in the future besides our BTRIS classes that use an external registration site. So to prepare for that just add "External" under training format just like how the Webinar box is done. Then when it is selected to will bring up fields for External registration URL and title. And the red header can read "External Registration".

**Comment by mashanadavis** [comment]
Stan – Can we discuss this in more detail when I’m back in the office? I’m not clear on the registration for BTRIS. From what I can understand, BTRIS uses an external registration form, similar to our webinars.

**Comment by alwaysmashana** [comment]
During the last meeting, we discussed changing the webinar option to external registration. However, WebFirst wanted to discuss this further internally. Is there an update?

**Comment by gbohara** [comment]
See #53, for webinars this has already been addressed. I have outlined the scenarios that can be tested. 

About adding similar functionality for BTRIS, the discussion was  about whether to generalize and use same functionality for BTRIS or to create similar functionality (basically copying webinar)

**Comment by svpatel1** [comment]
Posted wires of possible use cases. We can continue discussion on basecamp as well: https://basecamp.com/2765815/projects/7275781/uploads/32473175?enlarge=234857160#attachment_234857160

**Comment by alwaysmashana** [comment]
Also posted to Basecamp:

The use cases make sense to us, so go forth and do. We could not think of additional use cases.

When will the functionality be in place as well as the layout/design? Can we expect to test this in BR2?

**Comment by svpatel1** [comment]
We will have this completed by BR2 (end of July), however, with this modification, all events will have to be re-entered. Let us know if there are any issues.

**Comment by alwaysmashana** [comment]
Thanks for the update. Is there way to export the existing content? Once the code is reworked, can we then re-import the data?

**Comment by alwaysmashana** [comment]
Validate when webinar selected.  The location should not be one of the physical location from the list.

**Comment by alwaysmashana** [comment]
Tested. My above comments were not implemented. 

See test entry: http://nihlibrary.prod.acquia-sites.com/training/api-application-program-interface/test-after-implementation-ticket-190

Location = Porter, Format = webinar.

**Comment by svpatel1** [comment]
sorry MaShana, we'll take care of it.

**Comment by alwaysmashana** [comment]
Functionality on STG. It will be moved to PROD.

**Comment by stanleymurgolo** [comment]
I believe they just fixed this when fixing #205. MaShana do you want to take a look before I close?

**Comment by alwaysmashana** [comment]
Let me check.
