### ISSUE TITLE
Inserting an image

### ISSUE THREAD

**Issue by stanleymurgolo** [NIHL/Drupal7-Migration#196]
Did the way you insert an image change? All I see now is select an image's url path. You use to be able to select the file.

**Comment by stanleymurgolo** [comment]
Something is wrong with the WYSIWYG perhaps. You use to be able to insert an image into the content field when setting up a news story or training session. Now that option is gone. Instead it asks for an image url path to insert an image. I've tried inserting the images url path and it still doesn't work.

**Comment by stanleymurgolo** [comment]
A news story has a media option this can be a work around for the news section, but it would be nice to have the option to add images to the content field again, in both the news and training sections.

**Comment by alwaysmashana** [comment]
We're using this workaround until the WYSIWYG is fixed:

1.      Open browser window to desired content page.
2.      Open another browser window/tab to display image files: http://nihlibrary.prod.acquia-sites.com/admin/content/file/thumbnails or Home > Administration > Content > Files > Thumbnails.
3.      Find place in text to add image and click Image icon from WYSIWYG.
4.      In the browser window/tab from Step #2, find the image and R-click to select View Page Info.
5.      On the Media tab, find the URL in the Address list, R-click to Copy.
6.      In the browser window/tab from Step #1, add the URL. The URL should read: "/sites/default/files/[image name]."
7.      Save and the image will appear.

**Comment by gbohara** [comment]
Stanley, you mentioned NEWS and TRAINING SESSION.
 Is there any reason not have ability to add images through WYSIWYG in any other content?

**Comment by gbohara** [comment]
Also, seems like the media field added in the NEWS was work around to insert images in the NEWS at the top.

I don't think we need that media tab in the NEWS to insert pictures at the top, once we are able to enter images through WYSIWYG.

For the record, I will go ahead and create another ticket to delete the media(tab) from the NEWS.

**Comment by gbohara** [comment]
Please go ahead and test this. Clicking on the image should let you browse media server.
I haven't tested uploading images yet. Please do test uploading images as well.

**Comment by stanleymurgolo** [comment]
Hi Ganga, I agree I don't think we need the media tab.

**Comment by stanleymurgolo** [comment]
I tried testing this on the production server and didn't see a change.

**Comment by svpatel1** [comment]
Stanley - please try selecting "extended html" (not filtered) and you will see the upload tab for images... We have fixed the workaround.

**Comment by alwaysmashana** [comment]
The default text format is Filtered HTML. Should this be updated?

**Comment by alwaysmashana** [comment]
Changes implemented. Closing ticket.

**Comment by gbohara** [comment]
For the news that are already created,  by default it picks the format that was originally used. 
ie. (If  "filtered html" was picked at the time creation / last update, it will show "filtered html")

For all the new ones, it will display "Extended HTML" by default.
