### ISSUE TITLE
Find out access rules for Journal, Database etc.

### ISSUE THREAD

**Issue by gbohara** [NIHL/Drupal7-Migration#197]
Based on June 6 meeting.

Specifics for Journal, databases etc w u/p that should be restricted. At agency lever or level X?

**Comment by gbohara** [comment]
![img_20160606_140055](https://cloud.githubusercontent.com/assets/14879144/16420717/6b90e0d8-3d20-11e6-9f5f-c2b2785db844.jpg)

**Comment by alwaysmashana** [comment]
Here's the list of resources with u/p:

- Cellular and Molecular Biology
- General Dentistry
- Journal of Reproductive Medicine
- Biological Therapies in Psychiatry Newsletter
- Medical Dictionary for Regulatory Activities-MedDRA
- Scopus (Papers code)

Please let me know if there is anything else you may need.

**Comment by gbohara** [comment]
MaShana,
How is that related to the current resources? Is there anything that identifies a resource falls in one of the categories in the list?

**Comment by alwaysmashana** [comment]
There's a small subset of resources that require a u/p and this field only displayed to authenticated users for that particular resource. There is no flag in the database. The u/p information for these resources is in the field labeled "Instructions." 

Below is the list again with the assigned customer group.

Cellular and Molecular Biology - NIHL
General Dentistry -HHS
Journal of Reproductive Medicine - NIIHL
Biological Therapies in Psychiatry Newsletter - HHS
Medical Dictionary for Regulatory Activities-MedDRA – NIHL
Scopus (Papers code) – NIHL and HHS

**Comment by tgifford-webfirst** [comment]
@alwaysmashana, I thought you mentioned some u/p resources were specific to an HHS sub-agency during our whiteboard session. Is that just a mis-remembrance?

**Comment by alwaysmashana** [comment]
I confirmed with our ER librarians and this is the list. There are three resources linked to HHS: General Dentistry, Biological Therapies in Psychiatry Newsletter, and Scopus (Paper code).

**Comment by alwaysmashana** [comment]
Bridget is working with John on this. As of today, the e-resources were re-indexed, so the subjects should be aligned. John is working to update the view on the search results page to display, specifically for the e-resources. The display should reflect the decision on Basecamp: https://basecamp.com/2765815/projects/7275781/documents/11238558.

**Comment by alwaysmashana** [comment]
The content that includes information in the Notes field was identified. This ticket can be closed.
