### ISSUE TITLE
Change option under Log In mega menu from "NIH Staff" to "NIH Library Staff"

### ISSUE THREAD

**Issue by mashanadavis** [NIHL/Drupal7-Migration#20]
How do you update this? Is this in the code?

**Comment by tgifford-webfirst** [comment]
Now that the dropdown is gone, so is the NIH Staff option. Do we need to add an "NIH Library Staff" link on the login page?

**Comment by jronmorgan** [comment]
I believe what you are looking for is found by clicking on the NIH option in the table. It may not have the label "NIH Library Staff" and is in the second ugly yellow table on the page (sorry,  I wasn't worried about looks until we decided for sure what we wanted.)

-john

________________________________

**Comment by mashanadavis** [comment]
Our staff needs a place to log into the site. If the Login page is the best place, then I'm fine with that. I will let others chime in.

**Comment by tgifford-webfirst** [comment]
The link John mentioned is an EZProxy link. It sounds like Mashana is talking about the Drupal login page, which was one of the options in the dropdown.

**Comment by cmndr-king** [comment]
My draft login page for EZProxy includes a library staff option.

-James
_______________________________
James King, MLS, FSLA
(301) 496-2187

http://about.me/cmndr_king

**Comment by jronmorgan** [comment]
I'll go back and take a look. I haven't deleted anything.
However you can log in to the actual Drupal site simply by typing /user

-john

________________________________

**Comment by cmndr-king** [comment]
this is for the content owners to login - not related to authentication

**Comment by mashanadavis** [comment]
I thought John added a link on the page. Maybe it was skipped.

**Comment by tgifford-webfirst** [comment]
I added the NIH Library Staff link: http://nihlibrarystg.prod.acquia-sites.com/signin/main

Do you want the link listed elsewhere in the table?

**Comment by mashanadavis** [comment]
It's almost as if the link should be pulled out of the table altogether. But if that's too complicated or not an agreeable solution then leave it in. If the latter, change the text in the agency column to read something like "NIH Library Staff (login for Drupal website)".

MaShana Davis, MIM
Information Architect
National Institutes of Health Library
Division of Library Services
Office of Research Services
10 Center Drive
Building 10, Room 1L13E, MSC 1150
Bethesda, MD 20892-1150
301.594.6470
mashana.davis@nih.gov<mailto:mashana.davis@nih.gov>

Stay connected with the NIH Library
NIH Library: http://nihlibrary.nih.gov
Facebook: http://www.facebook.com/nihlibrary
Twitter: http://www.twitter.com/nihlib
------------------------------------------
Your Partner in Research




On Mar 15, 2016, at 6:31 PM, tgifford-webfirst <notifications@github.com<mailto:notifications@github.com>> wrote:


I added the NIH Library Staff link: http://nihlibrarystg.prod.acquia-sites.com/signin/main

Do you want the link listed elsewhere in the table?

**Comment by tgifford-webfirst** [comment]
The options include:

1. Move the link to the last row of the table
1. Move it to a new paragraph at the bottom of the page.
1. Put the link in a block that only displays on the login page for NIH IP addresses.
1. Remove it and teach content editors to access /user (or /user/login) manually.

Option 3 is slightly more work than option 2, but I think those are the best options. Please pick one, then tweak the text below if desired. 

> [Login for NIH Library content editors](http://nihlibrarystg.prod.acquia-sites.com/user/login)

**Comment by mashanadavis** [comment]
I like Option 2 and the text above. When we release the first beta site, our staff will have an opportunity to provide feedback. We'll see how many of them find it difficult to locate the link on the login page.

**Comment by mashanadavis** [comment]
Based on our meeting, we are still working on the layout for this page; but the link placement and wording is fine. 

Closing the ticket.
