### ISSUE TITLE
Remove Customer Groups and any other taxonomy from News listsing / news pages

### ISSUE THREAD

**Issue by gbohara** [NIHL/Drupal7-Migration#202]
http://nihlibrarystg.prod.acquia-sites.com/about-us/news/omiccircos-data-visualization-data-integration-april-21

**Comment by gbohara** [comment]
The categories listing should contain terms under following vocabularies.
* NIH Subject
* Tags

**Comment by alwaysmashana** [comment]
Clicking on More should display all the terms in the same page

**Comment by gbohara** [comment]
Here are some improvements that we can make for this page.
* Remove Recent News 
   (These are the news that are already being displayed in the page and it is just duplicate of what is already there)
* Separate news categories on the left side bar into "NIH Subject" and "Tags".
  The search results page has both NIH Subject and tags. To be consistent, I think it is better to separate these two. Furthermore, some of the tags and NIH subject can overlap (eg. 3d printing). If we do not separate these, it might confuse users because they are going to see 2 "3d printing" one from NIH Subject and another from tags.

**Comment by gbohara** [comment]
The breadcrumb does not work for this at this point. I will go ahead and create another ticket for breadcrumb.
