### ISSUE TITLE
Provide help message for Customer group field

### ISSUE THREAD

**Issue by gbohara** [NIHL/Drupal7-Migration#203]
The customer group field needs some help text for content administrators.
* This applies for all the content types using Customer Group field.

**Comment by gbohara** [comment]
![customer-group-field-help-text](https://cloud.githubusercontent.com/assets/14879144/16994525/bc2edb88-4e75-11e6-970a-0b469f997911.png)

**Comment by alwaysmashana** [comment]
Forms containing the Customer Group field was updated.
