### ISSUE TITLE
Getting Access Denied when adding training session

### ISSUE THREAD

**Issue by stanleymurgolo** [NIHL/Drupal7-Migration#205]
I am getting an Access Denied message when adding a training session.

**Comment by alwaysmashana** [comment]
I walked through the issue and received the same error message. The class was created but an Access Denied error appeared on saving. 

Created a hybrid (in-person and webinar), used the new widget, but the old location widget still appears. The class is available to NIH and HHS. I'm logged in as an Admin. 

Training (Parent) = MaShana's Test Training Parent for SM's Issue
Training Session (Child) = MaShana's Test for SM's Issue

**Comment by gbohara** [comment]
Reviewing this.

**Comment by gbohara** [comment]
This should be fixed now. Please go ahead and test

**Comment by stanleymurgolo** [comment]
tested. It's working now. thank you ganga.

**Comment by alwaysmashana** [comment]
Tested and working. Thanks for fixing this!
