### ISSUE TITLE
Remove Register tab from FAQ's edit page

### ISSUE THREAD

**Issue by alwaysmashana** [NIHL/Drupal7-Migration#207]
I found something interesting when editing the FAQs page (http://nihlibrary.nihlibrary.com/about-us/faqs), a tab labeled Register. The tab, when clicked, displays information about training and a link to the Suggest a Class form. 

I reviewed the FAQ content type but didn't see this listed. How can these two content types be linked?

**Comment by gbohara** [comment]
Thanks for testing this MaShana. I will look into it.

**Comment by alwaysmashana** [comment]
This tab is showing up in other content types. Logged in today and saw it on the Guide content type.
