### ISSUE TITLE
"More News" link on homepage is broken

### ISSUE THREAD

**Issue by alwaysmashana** [NIHL/Drupal7-Migration#208]
http://nihlibrary.nihlibrary.com/about-us/news/231%2C296

This link produces an error. When the characters after the last slash are removed the page renders correctly. Looking at the view, I cannot readily see where and how to fix this.

**Comment by gbohara** [comment]
This has been fixed. But the Agency ID's from the links needs to be removed.

**Comment by alwaysmashana** [comment]
Thanks for the fix, but can you explain what needs to be removed?

**Comment by gbohara** [comment]
The link on the homepage (More News) points to http://nihlibrary.prod.acquia-sites.com/about-us/news/231%2C296.

The last item in the URL (231%2C296) is not used in the views anymore. The initial idea was to show different results to different Customer Group based on these values.
Now it should be removed.

**Comment by alwaysmashana** [comment]
To confirm, this functionality (displaying info based on customer group) is handled by the agency_access field?

**Comment by alwaysmashana** [comment]
231%2C296 still appears in the URL.

**Comment by gbohara** [comment]
The Agency ID information removed from the URL
