### ISSUE TITLE
Change The Widgets of Customer Group Fields

### ISSUE THREAD

**Issue by gbohara** [NIHL/Drupal7-Migration#212]
Agency Homepage,
Alert Notice,
FAQ, 
Guide
News
Resource
Tool
Training Session
Webpage

**Comment by alwaysmashana** [comment]
Agency Homepage - same
Alert Notice - changed
FAQ - changed
Guide - changed
News - changed
Resource - changed
Tool - changed
Training Session - changed
Webpage - changed
