### ISSUE TITLE
In Person class wth External Registration

### ISSUE THREAD

**Issue by stanleymurgolo** [NIHL/Drupal7-Migration#213]
Using the new Training Format, I tried adding an on site (NIH Library Training Room), In Person Class *BUT* with an External registration such as a BTRIS class would be. The Registration link does not show when the class is published.

**Comment by stanleymurgolo** [comment]
Also not showing the registration form if its an in-person class but has an external vendor such as modeling proteins class on August 11

**Comment by gbohara** [comment]
Stanley,
I just tried and selected
*Location: NIH Library Training Room
*Training format: In-Person Class
*Type of registration: External Registration
and it seems to be working fine.  

Can you try it again and let me know what steps did you follow? 
Or I can walk-through

**Comment by stanleymurgolo** [comment]
I'm going to the August 3rd class. In the Training Location, Format and Registration section, I am entering NIH Library Training Room for Location, In-Person Class for Training format, and External Registration for Type of Registration. Then for the title of the External Registration I an putting "BTRIS Registration" and the URL is http://training.cit.nih.gov/class_details.aspx?cId=NIHCIT-LS564   When I publish it doesn't show the link and when I go back in it's not holding the information I input.

**Comment by gbohara** [comment]
This is actually not saving new Location, format and Registration. Working on it.

**Comment by alwaysmashana** [comment]
Stan - I spoke with Sanjay and Ganga this AM and they are going to remove training classes for August and September to fix this issue. The data will need to be re-entered once the issue is resolved.

**Comment by gbohara** [comment]
Training for August and September have been deleted. New trainings can now be entered.  

I have saved the whole database prior to saving (Just in case we need).
Please let me know if you encounter the same problem again.

**Comment by stanleymurgolo** [comment]
I am still having the issue. See August 3rd BTRIS class. The vendor is external, the location is the training room, in person class, external registration site. when i save the class and view the link is not there. when I go back in the fields are not populated.

**Comment by gbohara** [comment]
Thank you for testing Stanley. Will get back to you.

**Comment by gbohara** [comment]
I have noted and locally verified that if you select **External Vendor** as **Type of Instructor**,  this problem occurs.

Can you enter new training specifically having  **External Vendor** as **Type of Instructor** and see what happens?

**Comment by stanleymurgolo** [comment]
Entered new training with External Vendor, but it is not showing up

**Comment by gbohara** [comment]
Can you go ahead and try again?

**Comment by stanleymurgolo** [comment]
Hi Ganga, It's working now

**Comment by gbohara** [comment]
Thanks for verifying it Stanley.
