### ISSUE TITLE
eBooks link (on homepage) points to SharePoint site

### ISSUE THREAD

**Issue by alwaysmashana** [NIHL/Drupal7-Migration#214]
This link should point to http://nihlibrary.nihlibrary.com/search/site?f%5B0%5D=im_field_resource_type%3A1. 

How can this be updated in the future? Is this in the code?

**Comment by gbohara** [comment]
Which  Ebook link? 
The one in the "Explore Quick Links" section is pointing to the correct URL.

**Comment by alwaysmashana** [comment]
Given the changes to the homepage design, I don’t think we need to do this. We can revisit when the theme is implemented.

**Comment by alwaysmashana** [comment]
But, I would like the link updated now, if possible.
