### ISSUE TITLE
Instruction: Manage Registration - Links do not work - Settings and Email Registrants

### ISSUE THREAD

**Issue by mashanadavis** [NIHL/Drupal7-Migration#22]
Settings point to http://nihlibrarystg.prod.acquia-sites.com/node/566/registrations/settings - not sure what this page is supposed to look like. But, this is an unformatted website.

Email Registrants points to http://nihlibrarystg.prod.acquia-sites.com/node/566/registrations/broadcast and only displays an unformatted website. Not a form to do bulk email.

**Comment by tgifford-webfirst** [comment]
Both issues were fixed by #59. Your browser may complain, it appears to be a performance bug in the registration module, but if you use Chrome it should chug through it (Firefox also worked, eventually).

**Comment by mashanadavis** [comment]
It works...Yay!
