### ISSUE TITLE
Instruction: Moderating Trainings - how do you use this page?

### ISSUE THREAD

**Issue by mashanadavis** [NIHL/Drupal7-Migration#23]

**Comment by mashanadavis** [comment]
http://nihlibrarystg.prod.acquia-sites.com/node/551/moderation

**Comment by cmndr-king** [comment]
I think we've figured this out.

**Comment by mashanadavis** [comment]
James - Please write the answer in the ticket for KM purposes. For all questions, we probably should do this.


On Oct 1, 2015, at 3:56 PM, James King <notifications@github.com<mailto:notifications@github.com>> wrote:


I think we've figured this out.

**Comment by cmndr-king** [comment]
When a class is created, it is automatically placed in a review queue.  Someone with the right credentials must click on the Moderate tab and change the state from "Needs Review" to "Published".  Once that has been done, the class will show up on the site.
