### ISSUE TITLE
Breadcrumbs not established

### ISSUE THREAD

**Issue by mashanadavis** [NIHL/Drupal7-Migration#25]

**Comment by cmndr-king** [comment]
Do we need a tree?  How do we handle services?

**Comment by mashanadavis** [comment]
James - Please explain your question about a tree. Do you mean that we should create one---paper and pen---to show how breadcrumbs should be created, developed, operate, etc.?


On Oct 1, 2015, at 3:58 PM, James King <notifications@github.com<mailto:notifications@github.com>> wrote:


Do we need a tree? How do we handle services?

**Comment by cmndr-king** [comment]
Mashana - this was a note added in our meeting, trying to clarify what the ticket was about.  I believe we are trying to say that there is not a breadcrumb tree established when clicking on a service.  What do we want the breadcrumb to look like when someone clicks on a service?

**Comment by mashanadavis** [comment]
We had a long discussion about breadcrumbs with FEI, but this was never resolved. We should decide what type of breadcrumb to use: 
     location-based (where the user is in the website hierarchy), 
     attribute-based (displays attributes of a page), or
     path-based (shows user the steps taken to arrive at a particular page). 

Then we can figure out layout for the breadcrumbs and the number of layers. 

IMO, we should use location-based breadcrumbs to make it easier for the user. 

So for example, user X clicks on Bioinformatics Support Program from the Services mega menu. The breadcrumb should read: Home > Service > Bioinformatics Support Program. If the user clicks Databases and Analysis Tools, should there be an additional label added to the breadcrumb: Home > Service > Bioinformatics Support Program > Databases and Analysis Tools?

**Comment by tgifford-webfirst** [comment]
That sounds like a good approach, and this will therefore be dependent on the sitemap.

**Comment by mashanadavis** [comment]
The sitemap is saved on Basecamp and needs to be reviewed by James and/or Ben.

Ted - is this what you were looking for? Does this help those you an idea of what we need?




On Oct 26, 2015, at 1:46 PM, tgifford-webfirst <notifications@github.com<mailto:notifications@github.com>> wrote:


That sounds like a good approach, and this will therefore be dependent on the sitemap.

**Comment by tgifford-webfirst** [comment]
My understanding was that you were still working on documenting the "Needs Customizations for:" columns in the sitemap. If there is a lot of customization needed, we shouldn't start implementing the breadcrumbs yet.

**Comment by mashanadavis** [comment]
Ted - Are the customization options mutually exclusive?

**Comment by tgifford-webfirst** [comment]
Based on the discussion today, the breadcrumbs will be based on the active main menu, of which there will be three to choose from. No need to fill out the customizations columns now.

**Comment by cmndr-king** [comment]
Work on this ticket is interrelated with ticket 13 (services pages).  This effort also spawned a new ticket (69) to deal with a specific instance where breakcrumbs don't work correctly.
