### ISSUE TITLE
Agency Homepage: 4 features - title doesn't link to news item

### ISSUE THREAD

**Issue by mashanadavis** [NIHL/Drupal7-Migration#26]
Why not use the link or URL data type instead of text for the URL field? 

User story: User accesses featured news story from agency homepage. 

Required functionality: User clicks on image and/or title from homepage and is linked to a news story. There are two content types involved in this scenario: Agency Homepage and News. Each agency homepage contains 4 features that link to a news story.

**Comment by mashanadavis** [comment]
http://nihlibrarystg.prod.acquia-sites.com/admin/structure/views/view/list_features_home/edit/default?destination=node/25

**Comment by jronmorgan** [comment]
Fixed.

**Comment by mashanadavis** [comment]
The image and caption (story title) should link to a news item. The URL is part of the feature's data structure (or whatever its called). The homepage features are part of the Agency Homepage content type. They do not have their own content type---a field collection is being used to generate the features.
