### ISSUE TITLE
PHP Notice: Undefined index in view (probably due to missing/renamed field)

### ISSUE THREAD

**Issue by tgifford-webfirst** [NIHL/Drupal7-Migration#27]
See /content/3d-printing-nih-library-orientation.

**Comment by tgifford-webfirst** [comment]
The field that was removed is referenced in the "block_3" (Training Info) display of the training_sessions view. If you edit it there is a message that the broken relationship was fixed and the view needs to be saved: /admin/structure/views/view/training_sessions/edit/block_3

We should verify that this block display is still in use--I wasn't able to find a reference to it in /admin/structure/block or /admin/structure/context. If it is just cruft we can disable the display, or delete it entirely.

**Comment by mashanadavis** [comment]
/content/3d-printing-nih-library-orientation: This page no longer exist.  Where is the error again?

**Comment by tgifford-webfirst** [comment]
The page still exists on the dev site, although the error doesn't appear there, probably due to the views block in question no longer being displayed. In any case, the underlying issue is that the WoS Subject field (field_wos_subject) is currently referenced in the definition of the "Training Info" (block_3) display of the "Training Sessions" view. The field still exists on the Audio entity, so it appears a Relationship was removed from this view display (no audio file is currently referenced). If we don't need the "Training Info" block or the audio file, then we can safely save the view without the field in question.

Who will know whether we need the field or display?

**Comment by tgifford-webfirst** [comment]
The view was being shown on the registration page for training sessions, and doesn't appear to have any use for the WoS Subject field. Marking as fixed, there's no QA to do.

**Comment by mashanadavis** [comment]
The WoS Subject field is not in play anymore. This field referenced a taxonomy that was removed from the system.
