### ISSUE TITLE
Content Type: Staff Profile - Cannot select image from Library

### ISSUE THREAD

**Issue by mashanadavis** [NIHL/Drupal7-Migration#28]
Two options for adding an image to the staff profile: upload file or select from Library (saved images on Drupal site). Image selected but received an error "You have not selected anything!"

**Comment by tgifford-webfirst** [comment]
Was this on the dev or stg site?

**Comment by mashanadavis** [comment]
Sorry, I'm working in STG. Staying away from DEV as I know you are working on it.

**Comment by jronmorgan** [comment]
what is the link to this page? I can only find "Staff Directory" and "People" don't have images.

**Comment by mashanadavis** [comment]
This happens when you attempt to create a staff profile content type. Each profile should have an image, and you can upload or use one from the library (files on Drupal). But when you try to do the latter you get an error. Try to create this content type to reproduce the error.

MaShana Davis, MIM
Information Architect
National Institutes of Health Library
Division of Library Services
Office of Research Services
10 Center Drive
Building 10, Room 1L13E, MSC 1150
Bethesda, MD 20892-1150
301.594.6470
mashana.davis@nih.gov<mailto:mashana.davis@nih.gov>

Stay connected with the NIH Library
NIH Library: http://nihlibrary.nih.gov
Facebook: http://www.facebook.com/nihlibrary
Twitter: http://www.twitter.com/nihlib
------------------------------------------
Your Partner in Research




On Sep 22, 2015, at 6:12 PM, jronmorgan <notifications@github.com<mailto:notifications@github.com>> wrote:


what is the link to this page? I can only find "Staff Directory" and "People" don't have images.

**Comment by mashanadavis** [comment]
You have to create a staff profile to see the error: Content > Add Content > Staff Profile or http://nihlibrarystg.prod.acquia-sites.com/node/add/staff.

Here's a screenshot of the error message. I clicked on the Image button, selected Library and clicked on an existing image, and hit Submit. This is what I got. This should not occur and wasn't happening before. Not sure if this is a result of the Drupal update. 
![error-staffprofile-using-the-library-to-upload-image fw](https://cloud.githubusercontent.com/assets/13887931/10103634/00b902ea-6373-11e5-81c7-f24f7637223d.png)

**Comment by svpatel1** [comment]
We will take a look at this one as well, unless there are objections.

**Comment by mashanadavis** [comment]
No objections here.

**Comment by mashanadavis** [comment]
Replacing with ticket #106

This issue is across the site, not just related to this content type. 

Closing this ticket.
