### ISSUE TITLE
Content Type: Staff Profile - Area(s) of Interest header should be <H2> and the list should be displayed a comma delimited list

### ISSUE THREAD

**Issue by mashanadavis** [NIHL/Drupal7-Migration#31]

**Comment by tgifford-webfirst** [comment]
I implemented this by overriding a field template (tpl.php) file that outputs the links separated by commas. An alternative is to use ul/li markup to wrap the links, then append the commas using css :after pseudo-element, but I didn't think the additional complexity was worth it for this case.
