### ISSUE TITLE
Content Type: Staff Profile - Staff publications should be added as a block

### ISSUE THREAD

**Issue by mashanadavis** [NIHL/Drupal7-Migration#32]
Staff Publications is a new content type that needs to be added to the Staff Profile content type as a block. This may already be built into the theme, as any node block can be added to this content type.

**Comment by tgifford-webfirst** [comment]
It looks like the publications are not linked to the profiles. Let us know if you need assistance with this one.

**Comment by mashanadavis** [comment]
We are discussing this ticket. 

The dilemma: This attribute could be added to the Staff Profile content type, but what if we wanted a list of all staff publications or a list of publications for a particular group (e.g. Informationists or Librarians). How will/can this be achieved? This is a potential use case. 

Making staff publications or publications a separate content type might be the best solution. Can you advise on this potential use case?

**Comment by tgifford-webfirst** [comment]
I think it makes sense to have a separate content type for the publications, and in fact it already exists. I recommend adding a entity reference field on the staff publication content type to reference the associated staff profile. There may be a future need to link Staff Profiles to the associated Drupal user account/entity. This can be done with the author field, or with a new entity reference field on the staff profile, depending on the need.
