### ISSUE TITLE
php errors on content/3d-printing-nih-library-orientation

### ISSUE THREAD

**Issue by jronmorgan** [NIHL/Drupal7-Migration#33]
on page: http://nihlibrarystg.prod.acquia-sites.com/content/3d-printing-nih-library-orientation

**Comment by jronmorgan** [comment]
This has been fixed I believe.

**Comment by mashanadavis** [comment]
No error when logged in. Accessed class from link reported in issue, from Training & Events > Browse All Training > [class name], and from Home under Upcoming Training (clicked on session and got the registration form).
