### ISSUE TITLE
Instruction: Errors when creating a training content item

### ISSUE THREAD

**Issue by cmndr-king** [NIHL/Drupal7-Migration#35]
I'm creating a training content and will then create training sessions.  I've created one for EndNote and even though it said it was successful, I received several errors:

    Notice: Undefined index: reverse_field_wos_subject_node in views_handler_field_field->get_base_table() (line 149 of /mnt/www/html/nihlibrarystg/docroot/sites/all/modules/views/modules/field/views_handler_field_field.inc).
    Notice: Undefined index: in views_handler_field_field->access() (line 127 of /mnt/www/html/nihlibrarystg/docroot/sites/all/modules/views/modules/field/views_handler_field_field.inc).
    Notice: Undefined index: reverse_field_wos_subject_node in views_handler_field_field->get_base_table() (line 149 of /mnt/www/html/nihlibrarystg/docroot/sites/all/modules/views/modules/field/views_handler_field_field.inc).
    Notice: Undefined index: in views_handler_field_field->query() (line 186 of /mnt/www/html/nihlibrarystg/docroot/sites/all/modules/views/modules/field/views_handler_field_field.inc).
    Notice: Undefined index: entity keys in views_handler_field_field->query() (line 198 of /mnt/www/html/nihlibrarystg/docroot/sites/all/modules/views/modules/field/views_handler_field_field.inc).
![endnote-error-9-23](https://cloud.githubusercontent.com/assets/11525049/10048143/8e949aba-61df-11e5-8a60-6b2068479fe3.png)

**Comment by jronmorgan** [comment]
great…  I google the error messages to try and find solutions and the ONLY hit I get is THIS page where you reported the error.. :-P  lol..

**Comment by jronmorgan** [comment]
should be fixed I hope. I had to patch the following file to fix it: 

sites/all/modules/views/modules/field/views_handler_field_field.inc

diff --git a/docroot/sites/all/modules/views/modules/field/views_handler_field_field.inc b/docroot/sites/all/modules/views/modules/field/views_handler_fie
index a91e13a..b27b65c 100644
--- a/docroot/sites/all/modules/views/modules/field/views_handler_field_field.inc
+++ b/docroot/sites/all/modules/views/modules/field/views_handler_field_field.inc
@@ -146,7 +146,9 @@ class views_handler_field_field extends views_handler_field {
         if (!empty($relationships[$this->options['relationship']])) {
           $options = $relationships[$this->options['relationship']];
           $data = views_fetch_data($options['table']);
-          $this->base_table = $data[$options['field']]['relationship']['base'];
+
+          if (isset($data[$options['field']]) && isset($data[$options['field']]['relationship']['base']))
+            $this->base_table = $data[$options['field']]['relationship']['base'];
         }
       }
     }

**Comment by mashanadavis** [comment]
James - Please validate these issue. If fixed, remove "fixed-please validate" label and add "validated label, then move it to the proper queue in Waffle and close on GitHub.

**Comment by cmndr-king** [comment]
Created a class and didn't see the errors - marking as done.
