### ISSUE TITLE
Instruction: Disable registration doesn't work

### ISSUE THREAD

**Issue by cmndr-king** [NIHL/Drupal7-Migration#36]
I have a BTRIS class that is using its own registration so I chose "Disable Registration" on that pull-down but it doesn't allow me to do so.  It gives me an error that it is a required field so I can't choose disable from the pull down.  We should be able to either use our default registration, point to a URL as an external registration, or disable registration.

**Comment by jronmorgan** [comment]
How do you navigate to find "Disable Registration"?  /admin/config/people/accounts ?

**Comment by cmndr-king** [comment]
When scheduling a class session, one of the options near the bottom is a pull-down select list that has registration form enabled by default.  The only other option is Disable Registration but when you do that and try to save the form, it says that it is a required field and will not proceed.  Look at the BTRIS record for an example of one that I wanted to disable the registration form.


-James
_______________________________
James King, MLS, FSLA
(301) 496-2187

http://about.me/cmndr_king

**Comment by jronmorgan** [comment]
I have set the field in question as "not required". Please validate that this causes no other issues.

**Comment by mashanadavis** [comment]
James - Please validate these issue. If fixed, remove "fixed-please validate" label and add "validated label, then move it to the proper queue in Waffle and close on GitHub.

**Comment by mashanadavis** [comment]
James - Please validate these issue. If fixed, remove "fixed-please validate" label and add "validated label, then move it to the proper queue in Waffle and close on GitHub.

**Comment by cmndr-king** [comment]
Tested and it works.
