### ISSUE TITLE
Instruction: Training not showing up

### ISSUE THREAD

**Issue by cmndr-king** [NIHL/Drupal7-Migration#37]
I've entered a couple classes into the system but they are not showing up on the home page.

**Comment by mashanadavis** [comment]
Are these TRAINING OR TRAINING SESSIONS? If the latter, you have to approve them prior to saving. Look under Publishing Status toward the bottom of the record. It probably says DRAFT. It should be set to PUBLISHED to appear on the website. Each time you make an edit or add a new session, the status has to be updated. Speaking from experience and frustration…

**Comment by cmndr-king** [comment]
That was it - user error. ;-)
