### ISSUE TITLE
Instruction: Location change

### ISSUE THREAD

**Issue by cmndr-king** [NIHL/Drupal7-Migration#39]
I've modified the location field within the training session instruction type to include webinar.  However, the widget on the instruction page doesn't show it.  Does that widget need to be manually amended?

**Comment by mashanadavis** [comment]
James - Can you clarify which widget you're referring to? Add the URL.

**Comment by tgifford-webfirst** [comment]
These views ([calendar](http://nihlibrarystg.prod.acquia-sites.com/node/161), [list](http://nihlibrarystg.prod.acquia-sites.com/node/166), and [browse](http://nihlibrarystg.prod.acquia-sites.com/node/186)) are using "grouped filters" to "alias" the taxonomy terms just for the filter. Therefore, the views have to be updated each time a taxonomy term is added or removed (and possibly renamed). This could be avoided with code, but if the terms don't change often, you could continue with this approach for the time being. It looks like all the views have been updated, hence Mashana's request for the specific URL and widget.

**Comment by mashanadavis** [comment]
This is not the approach that we want as the subjects may change more often. The subjects widget should be current as it relates to search across the site.

To this I will add that we want to know how the taxonomy (NIH Subject) works when importing new content types, specifically ERM data. If a term is in the import file will it be added if not already in the taxonomy?

On Oct 26, 2015, at 1:24 PM, tgifford-webfirst <notifications@github.com<mailto:notifications@github.com>> wrote:


These views (calendar<http://nihlibrarystg.prod.acquia-sites.com/node/161>, list<http://nihlibrarystg.prod.acquia-sites.com/node/166>, and browse<http://nihlibrarystg.prod.acquia-sites.com/node/186>) are using "grouped filters" to "alias" the taxonomy terms just for the filter. Therefore, the views have to be updated each time a taxonomy term is added or removed (and possibly renamed). This could be avoided with code, but if the terms don't change often, you could continue with this approach for the time being. It looks like all the views have been updated, hence Mashana's request for the specific URL and widget.

**Comment by tgifford-webfirst** [comment]
Sorry for being imprecise: the subjects filter is *not* using the "grouped" approach, it is format, location, and category that are "grouped". If subject is the only filter that will change frequently, then there is not urgent need to change anything.

Regarding the terms and import, I will defer to John.

**Comment by tgifford-webfirst** [comment]
Looks like we can close this. I'll create a new ticket for the new subject in ERM import and assign it to John.

**Comment by cmndr-king** [comment]
Marking as closed.
