### ISSUE TITLE
Assign pages for menu options under Training & Events

### ISSUE THREAD

**Issue by jronmorgan** [NIHL/Drupal7-Migration#40]
I could be wrong in the intended targets however on the main menu "Training & Events" pulldown 

Browse All Training
Classes & Webinars
Online Guides

All three of these point to the same node /node/186

Is this as intended?

**Comment by mashanadavis** [comment]
For now, yes. But eventually the targets will be changed. The instruction team (James) would inform us on the options. We haven't set up some of the content like the online guides.

MaShana Davis, MIM
Information Architect
National Institutes of Health Library
Division of Library Services
Office of Research Services
10 Center Drive
Building 10, Room 1L13E, MSC 1150
Bethesda, MD 20892-1150
301.594.6470
mashana.davis@nih.gov<mailto:mashana.davis@nih.gov>

Stay connected with the NIH Library
NIH Library: http://nihlibrary.nih.gov
Facebook: http://www.facebook.com/nihlibrary
Twitter: http://www.twitter.com/nihlib
------------------------------------------
Your Partner in Research




On Sep 25, 2015, at 7:55 AM, jronmorgan <notifications@github.com<mailto:notifications@github.com>> wrote:


Assigned #40<https://github.com/NIHL/Drupal7-Migration/issues/40> to @mashanadavis<https://github.com/mashanadavis>.

**Comment by mashanadavis** [comment]
Pages were created for each link under this mega menu. The content can be changed, if needed.
