### ISSUE TITLE
Instruction: Evaluate Instruction workflow

### ISSUE THREAD

**Issue by cmndr-king** [NIHL/Drupal7-Migration#42]
Training and Training Session are confusing and more work than we need.  The workflow requests the same information in both steps.  Can we make sure this is a module and could we possibly only use Training Session level?

**Comment by mashanadavis** [comment]
James - I don't think FEI used a module, rather content types with dependencies. But it's worth confirming before moving onto solution B---using Training Session only.

Ideally, the workflow should be to enter a class and all of its metadata, then the dates the sessions will be held. So date should be a repeated field, and also include a range for events that last longer than one day.

On Oct 1, 2015, at 3:54 PM, James King <notifications@github.com<mailto:notifications@github.com>> wrote:


Training and Training Session are confusing and more work than we need. The workflow requests the same information in both steps. Can we make sure this is a module and could we possibly only use Training Session level?

**Comment by cmndr-king** [comment]
In the kickoff discussion, we started to discuss the possibility of making NIHL the training level and creating class sessions under it, essentially hiding one level of complexity.  We need to flesh this out further.

**Comment by mashanadavis** [comment]
Review offline workflow. Does it reflect what can be done online? What enhancements need to be made to improve it? 

Consider for Phase 2 perhaps?

**Comment by alwaysmashana** [comment]
Stan - Please see my comments above.

**Comment by alwaysmashana** [comment]
Moved to https://github.com/NIHL/Drupal-Content-Migration/issues/43. Closing ticket.
