### ISSUE TITLE
Fix authentication through EZProxy

### ISSUE THREAD

**Issue by cmndr-king** [NIHL/Drupal7-Migration#44]
Figure out how to use EZProxy to pass to the correct landing page and filter content to the correct material tagged for that customer.

**Comment by svpatel1** [comment]
test

**Comment by svpatel1** [comment]
As James mentioned, WebFirst is working on the personalization on the drupal site as well (i.e. after an agency name is passed in, ensure that the page is displaying the correct quicklinks, ads, etc. for that agency).  John M. is working to understand how we can pass more info (e.g. subagency) from ezproxy.

**Comment by jronmorgan** [comment]
Just posting this here so that you can take a look also. the page http://www.oclc.org/support/services/ezproxy/documentation/url/form.en.html has a description of using an external form to send data that should be passed thru to the "database". Seems as if no configuration is necessary however I am trying to setup a test. Please let me know if you've already looked at this and rules it out (no point in wasting time if we already know it does;t work).

**Comment by tgifford-webfirst** [comment]
The issue with the Form directive is that it relies on the user to select the right sub-agency, and requires remote users to submit two forms (the login form, and the Form form).

**Comment by jronmorgan** [comment]
I am not sure that I see a way around users selecting the sub-agency. I don't recall anything that would key us to it unless there are specific IP's involved or we read his smart card directly via plugin.

Per the forms directive: I see what you mean. not a help.

________________________________

**Comment by 4benhope** [comment]
I think I may have worked this out in my head.  I’m documenting it in Visio and on paper now.


Ben Hope, MLS
Chief, Information Architecture Branch
National Institutes of Health Library
Division of Library Services
Office of Research Services
Bldg. 10, 1L19A, MSC1150
Bethesda, MD 20892-1150
(301) 594-6473
TallGuy@nih.gov<mailto:TallGuy@nih.gov>

Stay connected with the NIH Library
NIH Library: http://nihlibrary.nih.gov
Facebook: http://www.facebook.com/nihlibrary
Twitter: http://www.twitter.com/nihlib
_______________________
Your Partner in Research

**Comment by jronmorgan** [comment]
Per the sub-agency, whether they pick it or not, couldn't we simply pass the selected subagency via the target url and strip if off on the drupal side?  When we initially call EZproxy we pass it a target URL, why can't that URL contain the sub-agency? We have control over the page that calls EZproxy and we can modify things on the fly, there's no reason the urls have to be completely hard coded. 

Example:

We have control over the page: http://nihlibrary.ors.nih.gov/EZProxy/os2.htm 
We could put it under Drupal and add a required select list of sub-agencies to it. 

Example: user selects ASPE as the subagency. On change the url portion of the link would be updated before executing.  So:

https://itrusteauth.nih.gov/NIHLibrary/genOSticket.asp?url=http://nihlibrarystg.prod.acquia-sites.com/Agency/OS

would be rewritten as:

https://itrusteauth.nih.gov/NIHLibrary/genOSticket.asp?url=http://nihlibrarystg.prod.acquia-sites.com/Agency/OS/ASPE

The Drupal server then strip off the ASPE, logs it, sets the session values and sends out the /Agency/OS page by redirect (or some module code muckery).  If by simple redirect there should be no reason why the page can't be cached.  

Would this not work?

**Comment by jronmorgan** [comment]
Per the sub-agency, whether they pick it or not, couldn't we simply pass the selected subagency via the target url and strip if off on the drupal side?  When we initially call EZproxy we pass it a target URL, why can't that URL contain the sub-agency? We have control over the page that calls EZproxy and we can modify things on the fly, there's no reason the urls have to be completely hard coded. 

Example:

We have control over the page: http://nihlibrary.ors.nih.gov/EZProxy/os2.htm 
We could put it under Drupal and add a required select list of sub-agencies to it. 

Example: user selects ASPE as the subagency. On change the url portion of the link would be updated before executing.  So:

https://itrusteauth.nih.gov/NIHLibrary/genOSticket.asp?url=http://nihlibrarystg.prod.acquia-sites.com/Agency/OS

would be rewritten as:

https://itrusteauth.nih.gov/NIHLibrary/genOSticket.asp?url=http://nihlibrarystg.prod.acquia-sites.com/Agency/OS/ASPE

The Drupal server then strip off the ASPE, logs it, sets the session values and sends out the /Agency/OS page by redirect (or some module code muckery).  If by simple redirect there should be no reason why the page can't be cached.  

Would this not work?

I created a simple page for testing purposes and I tested this with the following link:

http://nihlibrarystg.prod.acquia-sites.com.ezproxyhhs.nihlibrary.nih.gov/Agency/ACF/ABCD

I then logged in with the drupal account and it proxies perfectly.

There seems to be nothing stopping us from changing ABCD to whatever we want before initiating the login sequence. ABCD doesn't have to be an actual page, it can just be a defined path which then redirects to the base page.

**Comment by tgifford-webfirst** [comment]
That approach works for the average user, but is insecure. If we are going to provide access info (see #43), then we have to find something else.

**Comment by jronmorgan** [comment]
Ok, given that #43 is no longer an issue here and given that we would run a post under ssl,  do you think the above scenario an acceptable solution? We can log the initial accesses on the drupal server side.

**Comment by jronmorgan** [comment]
I have not yet moved this code to dev but am just about ready to.

Changes I have made:

- Extensive changes to nihl_erm.module functions for accessing IP and agencies for the session
  - The "$collected" variable has been moved to the SESSION level
  - $collected and other session variables can be forced to reset on every call for dev 
- A new Content Type of Sign-in Page (Machine name: sign_in_page) has been created

Logic settings:
- When an un-signed in user hits the site he gets assigned agencies based upon the incoming IP
  - If an unknown IP the agency is set to Public
  - If the incoming IP is known the agencies are set to those associated with the known IP
    - The user does NOT have to sign in when using a known IP to get his agencies settings.
  - The variable _SESSION['nihl_erm_user_access']['signed_in'] will be set to === false
    - I am not yet entirely sure that this variable is useful but I have it in there for now

Session Variables set:
  _SESSION['nihl_erm_user_access']['ip'] 		- the raw user's IP address
  _SESSION['nihl_erm_user_access']['tids']		- the list of related agency tids
  _SESSION['nihl_erm_user_access']['agencies']`	- the list related agency term names
  _SESSION['nihl_erm_user_access']['signed_in']	- boolean - manually authenticated
  _SESSION['nihl_erm_user_access']['proxied']		- is EZproxy login
  _SESSION['nihl_erm_user_access']['collected']	- connection information collected

Questions:
- if the user is accessing from HHS and we need a subagency do we force him to select one before continuing or do we simply show the base IOS site until he elects to do sign-in?

Notes:
- It is suggested that you do not use the IP address in code to fork display logic as some Agency should *always* be set for you. 

Files Updated:
  sites/default/settings.php
  sites/default/modules/custom/nihl_erm/nihl_erm.logger.php - new file
  sites/default/modules/custom/nihl_erm/nihl_erm.module
  sites/default/modules/custom/nihl_forms/nihl_forms.module
      my_custom_log_in_form()
      my_custom_log_in_form_submit()

**Comment by jronmorgan** [comment]
Interesting how the text gets reformatted upon submission.. :(

**Comment by cmndr-king** [comment]
On 11/23, John noted that he is validating his code and pushing it to dev.  He also will propose two different approaches to the workflow since it appears to have redundant pages in the current flow.

**Comment by cmndr-king** [comment]
On 12/2, John showed the code working on stage but the most current code is on dev.  He is working on moving it to stage today.  He will confirm that he has an EZProxy account to test the authentication.  We also decided that we need to review and combine information on some of the authentication pages.

**Comment by jronmorgan** [comment]
All code has been moved to stage and is being tested. A new ticket #70 has been created for modifying the flow now that a working version can be seen.
