### ISSUE TITLE
Subjects facet on calendar and list view does not display

### ISSUE THREAD

**Issue by mashanadavis** [NIHL/Drupal7-Migration#45]
Calendar: http://nihlibrarystg.prod.acquia-sites.com/node/161
List: http://nihlibrarystg.prod.acquia-sites.com/node/166

**Comment by tgifford-webfirst** [comment]
Is this a request to convert the subject filter, which is currently an autocomplete textbox, to a list of checkboxes like the Method filter?

On a related note, the subject filter will not work because the view does not include a relationship to the Training content type, which is where the Subject is defined. Wasn't there some talk about merging the Training and Training Session content types?

**Comment by mashanadavis** [comment]
The Subjects list widget/facet used to be a multi-select list. If the relationship is broken it should be added back using the original widget. A checklist or linked list would be too long.

At this time we are not merging the training content types. Temporary solution: settle on the fields that belong to each type. There were many overlapping fields that caused the workflow to be confusing and daunting. I believe we are happy with what we have now.

There is a ticket to review the code related to the workflow and how these two fields interact and possible solutions for simplifying in the future. This is assigned to Ganga.

FOR JAMES: Do we need to hold off on this or set it to a low priority since we updates the fields?

MaShana Davis, MIM
Information Architect
National Institutes of Health Library
Division of Library Services
Office of Research Services
10 Center Drive
Building 10, Room 1L13E, MSC 1150
Bethesda, MD 20892-1150
301.594.6470
mashana.davis@nih.gov<mailto:mashana.davis@nih.gov>

Stay connected with the NIH Library
NIH Library: http://nihlibrary.nih.gov
Facebook: http://www.facebook.com/nihlibrary
Twitter: http://www.twitter.com/nihlib
------------------------------------------
Your Partner in Research




On Oct 23, 2015, at 1:55 PM, tgifford-webfirst <notifications@github.com<mailto:notifications@github.com>> wrote:


Is this a request to convert the subject filter, which is currently an autocomplete textbox, to a list of checkboxes like the Method filter?

On a related note, the subject filter will not work because the view does not include a relationship to the Training content type, which is where the Subject is defined. Wasn't there some talk about merging the Training and Training Session content types?

**Comment by tgifford-webfirst** [comment]
This is now fixed and working on stg with the current field and two-content-type setup.
