### ISSUE TITLE
Create individuals views for A-Z lists for online books, databases, journals, and overall A-Z list

### ISSUE THREAD

**Issue by mashanadavis** [NIHL/Drupal7-Migration#5]
Prepare a searchable and sortable View in Drupal of the content type "resource" and type = database.

**Comment by jronmorgan** [comment]
Where do you want this to be linked from? How should the user navigate to find this new search?

**Comment by mashanadavis** [comment]
At the outset, this view will be linked from the global navigation under Resources > Databases > A-Z List. It should point to a page similar to http://nihlibrary.nih.gov/ResearchTools/pages/default.aspx?srchType=ViewDatabases. But, this view can be created by me. The electronic resources data hasn't been imported yet.

**Comment by mashanadavis** [comment]
Updating this ticket to cover all views related to the ERM. Closing tickets 3 and 4.

**Comment by jronmorgan** [comment]
Do we want the search page to look like the link you provided above or like the existing search in the new site (eg): 
http://nihlibrarystg.prod.acquia-sites.com/search/site?f[0]=im_field_resource_type%3A1

**Comment by mashanadavis** [comment]
Instead of creating individual A-Z lists for each resource type, I thought we discussed using the fastest on the current search results page and preselect in the resource tight and adding that link into the global navigation under resources. To allow the user to browse all resources the facet should be set to all resource types and the user can filter down from there. Hopefully this makes sense.

**Comment by tgifford-webfirst** [comment]
On the call today, we discussed having the search page automatically filter resources (and any other content type with field_agency_access) based on the user's agency. This involves altering the Solr query with custom code.

**Comment by mashanadavis** [comment]
Sounds good. I will create the links to the canned searches and add to the menus. A new ticket (if one doesn't exist) should be created to assign content based on the agency.

**Comment by mashanadavis** [comment]
Link were added to each resource type.
