### ISSUE TITLE
ERM and EZProxy - how will configuration updates happen?

### ISSUE THREAD

**Issue by cmndr-king** [NIHL/Drupal7-Migration#50]
The current SQL database creates a field that contains the EZProxy configuration information, formatted like this:

"T Cochrane Library
U http://www.thecochranelibrary.com
DJ thecochranelibrary.com"

T equals the resource title, U is the resource URL and DJ is the resource URL stem.  All of this can be drawn dynamically from the record but the script that draws all of this together and places it into a txt configuration file is outside of Drupal.  Do we need to recreate this functionality or is there another approach to keeping EZProxy updated?

**Comment by tgifford-webfirst** [comment]
## Non-Drupal Options

The script could be kept where it is and altered, but the data maintained in Drupal would still have to be exported somehow. You can't connect directly to the Drupal database, so this approach would involve some Drupal.

## Drupal Options

There are several places to put an analogous script in Drupal. Let me know if you need more explanation on anything below.

### Script location
* Page in Drupal admin (copy/paste)
* Download generated .txt output from Drupal admin page
* Drush script output to .txt file (assumes a developer is running it)

### Script inputs
* None
* Selection of resources
* Single resource

### Implementation Options
* Computed Field on entity
* View
* Custom module/menu callback

**Comment by mashanadavis** [comment]
Similar to ticket #47.

**Comment by alwaysmashana** [comment]
Moved to https://github.com/NIHL/Drupal-Content-Migration/issues/42. Closing ticket.
