### ISSUE TITLE
Instruction: Facets need an AND operator not OR operator

### ISSUE THREAD

**Issue by mashanadavis** [NIHL/Drupal7-Migration#51]
The facets on the calendar view use an AND operator, but not on the list view.

**Comment by tgifford-webfirst** [comment]
It seems like it should be OR, at least for the Method facet/filter. That allows a user to search for webinar or in-person classes, without including special events. Similarly for location, a training can't be in more than one place, so OR makes sense. I can see the argument going either way for category and subject, so those are probably the facets you're referring to here. Is that correct?

**Comment by mashanadavis** [comment]
So if I wanted to search for "in-person classes related to Bioinformatics, how do I this with an OR operator?

The AND operator is between facets, not within facets/filters.


On Oct 26, 2015, at 1:28 PM, tgifford-webfirst <notifications@github.com<mailto:notifications@github.com>> wrote:


It seems like it should be OR, at least for the Method facet/filter. That allows a user to search for webinar or in-person classes, without including special events. Similarly for location, a training can't be in more than one place, so OR makes sense. I can see the argument going either way for category and subject, so those are probably the facets you're referring to here. Is that correct?

**Comment by tgifford-webfirst** [comment]
Ah, between facets, sorry for the confusion. Both views are configured the same in that regard, and you get the same results if you select "In-Person Class" for method and "-Bioinformatics Support Program" for Subject (under NIH Library Services). Not-a-bug?

**Comment by mashanadavis** [comment]
Can we change the facets to work together?

MaShana Davis, MIM
Information Architect
National Institutes of Health Library
Division of Library Services
Office of Research Services
10 Center Drive
Building 10, Room 1L13E, MSC 1150
Bethesda, MD 20892-1150
301.594.6470
mashana.davis@nih.gov<mailto:mashana.davis@nih.gov>

Stay connected with the NIH Library
NIH Library: http://nihlibrary.nih.gov
Facebook: http://www.facebook.com/nihlibrary
Twitter: http://www.twitter.com/nihlib
------------------------------------------
Your Partner in Research




On Oct 26, 2015, at 3:29 PM, tgifford-webfirst <notifications@github.com<mailto:notifications@github.com>> wrote:


Ah, between facets, sorry for the confusion. Both views are configured the same in that regard, and you get the same results if you select "In-Person Class" for method and "-Bioinformatics Support Program" for Subject (under NIH Library Services). Not-a-bug?

**Comment by tgifford-webfirst** [comment]
The facets are working together with AND semantics, as desired. Please try the search described in my previous comment.
