### ISSUE TITLE
Each agency should have its own global navigation

### ISSUE THREAD

**Issue by mashanadavis** [NIHL/Drupal7-Migration#57]
The menu labels will be the same across each agency, but the underlying options may differ. Content authors should be able to customize the menus. 

EXAMPLE: NIH's options will differ from IHS. NIH has access to Resources > UptoDate, where, IHS has access to Resources > DynaMed. 

Not sure if this will be fixed when the authentication issues are resolved. And, I'm not sure if using the Drupal Menus module will help either. I think FEI was trying to accommodate this using these two things.

This ticket is related to #10.

**Comment by tgifford-webfirst** [comment]
There are several components to menu customization: 

* visibility
* text (e.g. "UptoDate" vs. "UptoDate for NIH")
* slight tweaks to the URL (e.g. add a "destination" query parameter)
* position in the menu

We need to determine which of the above customizations are required before we can select an implementation approach. The most complicated requirement would be altering the position of links in the menu per access context/agency; we should avoid that if possible.

**Comment by tgifford-webfirst** [comment]
If we end up with multiple main menus, [Multiple Node Menus](https://www.drupal.org/project/multiple_node_menu) will be useful.

**Comment by tgifford-webfirst** [comment]
Comments on latest sitemap have been posted to Basecamp.

**Comment by tgifford-webfirst** [comment]
Comments on latest sitemap posted to Basecamp.

**Comment by tgifford-webfirst** [comment]
This is ready for testing on stg. I've customized most of the menu items documented in the sitemap. Some links are just placeholders and need the URLs to be updated. To see the links in the menu change, you will need to switch to another customer group, either by logging in via EZProxy, or using the testing links I'll post to Basecamp. We should review the changes, including new options on the menu link edit page, at our next status meeting.

If we determine that new views need to be created to e.g. filter ERM resources by customer group, we can create new tickets for those.

**Comment by mashanadavis** [comment]
During the meeting we identified some errors (displaying  two Databases sections/headers) with the navigation on CMS and HHS. Also, how do you change the order of the sections/headers?

**Comment by tgifford-webfirst** [comment]
The two "Databases" in the secondary menu has been resolved, but there is still an issue with the global nav that I will fix today.

The order of the sections and headers is controlled by the weight of menu items on the ["List links" page](http://nihlibrarystg.prod.acquia-sites.com/admin/structure/menu/manage/main-menu), combined with settings in the [TB megamenu config page](http://nihlibrarystg.prod.acquia-sites.com/admin/structure/tb-megamenu/main-menu/config).

**Comment by mashanadavis** [comment]
Ted, the issue is cleared up. However, can you walk me through the workflow of the user? John is adding the ERM data and may add views for journals, books, and databases (at some point), so I'm trying to see how these two things interrelate.

**Comment by tgifford-webfirst** [comment]
Discussed user workflow with Mashana via phone.
