### ISSUE TITLE
PHP out-of-memory errors

### ISSUE THREAD

**Issue by tgifford-webfirst** [NIHL/Drupal7-Migration#59]
These were seen on several pages on Oct 1, 5, 6, and 7 on the stg site. The memory limit is at a reasonable value, so we should probably [adjust it on a per-request basis in the settings.php file] (https://docs.acquia.com/articles/conditionally-increasing-memory-limits).

 * GET /admin/config/search/path/patterns
 * GET /node/xxxx/registrations/settings
 * GET /node/yyyy/registrations/settings
 * GET /sites/default/files/styles/media_thumbnail/public/images/staff/StaffProfile-Stakes.jpg?itok=xxxx

**Comment by mashanadavis** [comment]
Explain this solution please. Should John confirm this to close?

**Comment by tgifford-webfirst** [comment]
I added code to the settings.php file to increase the memory limit on pages matching the patterns above. The reasons we are not trying to reduce the memory usage are outlined for each item below. In the case of the first two URLs, the large memory use corresponds to a very slow page load and user interface for site admins, which could possibly be followed-up in another ticket, if you feel it is not tolerable.

 * GET /admin/config/search/path/patterns

   This page loads large lists of tokens that can be inserted in the path patterns. Only administrators use this page, and rarely at that, so increasing the memory usage will not adversely impact the application.

 * GET /node/xxxx/registrations/settings

   This is another admin-only page that is accessed rarely. The root cause for memory usage is once again tokens.

 * GET /sites/default/files/styles/media_thumbnail/public/images/staff/StaffProfile-Stakes.jpg?itok=xxxx

   This URL refers to a static JPEG file that is generated the first time it is requested. To produce it, Drupal loads the source image, and then resizes it and performs other operations as specified for the media_thumbnail image style. If the source image is large, loading it will require large amounts of memory. This can be avoided only by requiring smaller original images to be uploaded. However, the media_thumbnail only needs to be generated once per source image, so we recommend raising the memory limit instead of restricting the image upload size.

**Comment by tgifford-webfirst** [comment]
The fact that the pages load at all means we can close the ticket--the PHP errors seen before the fix caused the requests to fail (WSOD).

**Comment by cmndr-king** [comment]
Marking as closed.
