### ISSUE TITLE
Message needed when registration has closed for a class.

### ISSUE THREAD

**Issue by mashanadavis** [NIHL/Drupal7-Migration#60]
The link to past training sessions points the registration form. For example, Creating Infographics with Inkscape http://nihlibrarystg.prod.acquia-sites.com/content/creating-infographics-inkscape-0/register. 

The user should see the metadata for the class --> title, description, date, time, location, subject(s), supplemental materials, etc.).

**Comment by tgifford-webfirst** [comment]
The registration module comes with a default message, you just need to provide a Close Date on e.g. http://nihlibrarystg.prod.acquia-sites.com/node/1141/registrations/settings. We could 
* make the Close Date a required field, or 
* default Close Date to the Training Session date, or
* add a reminder message for Trainers/Editors to specify a Close Date if one is not provided

The view that shows the metadata at the top also needs to be updated to remove the "You are registering" text if registration is closed.
