### ISSUE TITLE
The training session list uses content path alias to construct /register links, which doesn't work

### ISSUE THREAD

**Issue by tgifford-webfirst** [NIHL/Drupal7-Migration#62]
There are no automatic aliases for the /register links, so they should be constructed with the underlying path (node/x). See http://nihlibrarystg.prod.acquia-sites.com/content/creating-infographics-inkscape-0/register vs http://nihlibrarystg.prod.acquia-sites.com/node/1141/register.

**Comment by mashanadavis** [comment]
I removed the aliases until the path settings page is fixed. When you create content you have to uncheck the option to automatically generate an alias. This will resolve the links to the node. This is probably what Ted is saying.

**Comment by tgifford-webfirst** [comment]
I don't think there are any links to the (previously) aliased path for anonymous users, so you may not need to restore the path patterns once you have verified this is fixed. Up to you--the site could use a little less node/num.

**Comment by mashanadavis** [comment]
I would like to use content/ for the paths, but I need to patterns page fixed. This is another PHP error, and there was a ticket submitted for this.

MaShana Davis, MIM
Information Architect
National Institutes of Health Library
Division of Library Services
Office of Research Services
10 Center Drive
Building 10, Room 1L13E, MSC 1150
Bethesda, MD 20892-1150
301.594.6470
mashana.davis@nih.gov<mailto:mashana.davis@nih.gov>

Stay connected with the NIH Library
NIH Library: http://nihlibrary.nih.gov
Facebook: http://www.facebook.com/nihlibrary
Twitter: http://www.twitter.com/nihlib
------------------------------------------
Your Partner in Research




On Oct 16, 2015, at 5:23 PM, tgifford-webfirst <notifications@github.com<mailto:notifications@github.com>> wrote:


I don't think there are any links to the (previously) aliased path for anonymous users, so you may not need to restore the path patterns once you have verified this is fixed. Up to you--the site could use a little less node/num.

**Comment by mashanadavis** [comment]
Ted, can you explain the solution here?

**Comment by tgifford-webfirst** [comment]
The solution was to change the training session list and calendar view to generate the registration paths using node/[nid]/register, instead of the training session node alias. For example, consider the christmas day training session [node/1231](http://nihlibrarystg.prod.acquia-sites.com/node/1231), with alias [content/christmas-webinar-james](http://nihlibrarystg.prod.acquia-sites.com/content/christmas-webinar-james). The correct registration link for this session is [node/1231/register](http://nihlibrarystg.prod.acquia-sites.com/node/1231/register), not [content/christmas-webinar-james/register](http://nihlibrarystg.prod.acquia-sites.com/content/christmas-webinar-james/register). However, prior to the fix, the views were using that incorrect alias-based path.

If you would like to be able to use the aliased paths for the register links, we will either need to do some custom coding to keep the */register aliases in sync, or install the [subpathauto module](https://www.drupal.org/project/subpathauto), which comes with its own set of tradeoffs. If you would like to pursue either approach, let's do that in a new ticket.

The error on the url alias pattern page was fixed by increasing the memory limit in #59.
