### ISSUE TITLE
Check functionality of search facets on all search-related pages

### ISSUE THREAD

**Issue by mashanadavis** [NIHL/Drupal7-Migration#64]
See tickets #39, #45, #52, and #51. These are mainly related to the training calendar, but there are facets on the search page: http://nihlibrarystg.prod.acquia-sites.com/search/site.

**Comment by tgifford-webfirst** [comment]
The training calendar has issues with the Subject filter not working at all (see #45). Also, the location and category are supposed to render as radios/checkboxes, but that isn't happening. All of the above issues are related to Views.

The facets on the search page are implemented through the solr integration and facet api (not views), and appear to be working great. Did you have a specific concern?

**Comment by mashanadavis** [comment]
Search and facets working, but functionality could be cleaned up. Moving this ticket back to In-Progress. 

FOR TESTING:
Conducted a search on "bioinformatics."

**Comment by tgifford-webfirst** [comment]
@mashanadavis noted that sometimes facets disappear when selecting another facet. This is the behavior of AND-facets in the Drupal FacetAPI system; the hidden facets, if shown and selected, would produce an empty result set, so the system doesn't allow selecting them. This is the only behavior supported by AND-facets.

OR-facets do show facets that don't match/intersect the current search, but only allow expanding the search, not narrowing it. Any facet can be converted between AND and OR with a simple configuration change.

The choice of AND or OR should be considered for each facet, based on how the content is tagged, and how users can best search for it. OR facets are best suited to facets with items that are mutually exclusive, e.g. non-overlapping ranges or taxonomies where only one term can be selected. In general, AND facets work best when multiple terms can be applied to each content item. User search patterns and common sense can override those general rules. In addition, some taxonomies, such as NIH Subjects, are heterogeneous, and make the decision more complicated.

If you find that some users have a unique search requirement, you may be able to meet it with a dedicated View, or custom code as a last resort. For example, Views can be configured to allow the user to choose between AND/OR semantics within each filter.
