### ISSUE TITLE
Review "Node-Level Blocks" for compatibility with new Secondary Menu block

### ISSUE THREAD

**Issue by tgifford-webfirst** [NIHL/Drupal7-Migration#72]
For each block, check:

1. Are links redundant?
2. Does the node-level-block show up on all pages it needs to show on?
3. Does the block have a title/header?

See the following nodes:

| nid  | has blocks in region(s)    |
|------|----------------|
|   [24](http://nihlibrarystg.prod.acquia-sites.com/node/24) | sidebar_first  |
|   [45](http://nihlibrarystg.prod.acquia-sites.com/node/45) | sidebar_first  |
|   [51](http://nihlibrarystg.prod.acquia-sites.com/node/51) | sidebar_first, sidebar_second |
|  [161](http://nihlibrarystg.prod.acquia-sites.com/node/161) | content        |
|  [166](http://nihlibrarystg.prod.acquia-sites.com/node/166) | content        |
|  [296](http://nihlibrarystg.prod.acquia-sites.com/node/296) | sidebar_first  |
|  [301](http://nihlibrarystg.prod.acquia-sites.com/node/301) | sidebar_first  |
|  [311](http://nihlibrarystg.prod.acquia-sites.com/node/311) | sidebar_first  |
|  [321](http://nihlibrarystg.prod.acquia-sites.com/node/321) | sidebar_first  |
|  [326](http://nihlibrarystg.prod.acquia-sites.com/node/326) | sidebar_first  |
|  [331](http://nihlibrarystg.prod.acquia-sites.com/node/331) | sidebar_first  |
|  [336](http://nihlibrarystg.prod.acquia-sites.com/node/336) | sidebar_first  |
|  [341](http://nihlibrarystg.prod.acquia-sites.com/node/341) | sidebar_first  |
|  [346](http://nihlibrarystg.prod.acquia-sites.com/node/346) | sidebar_first  |
|  [356](http://nihlibrarystg.prod.acquia-sites.com/node/356) | sidebar_first  |
|  [361](http://nihlibrarystg.prod.acquia-sites.com/node/361) | sidebar_first  |
|  [366](http://nihlibrarystg.prod.acquia-sites.com/node/366) | sidebar_first  |
|  [371](http://nihlibrarystg.prod.acquia-sites.com/node/371) | sidebar_first  |
|  [376](http://nihlibrarystg.prod.acquia-sites.com/node/376) | sidebar_first  |
|  [381](http://nihlibrarystg.prod.acquia-sites.com/node/381) | sidebar_first  |
|  [386](http://nihlibrarystg.prod.acquia-sites.com/node/386) | sidebar_first  |
| [1101](http://nihlibrarystg.prod.acquia-sites.com/node/1101) | sidebar_first  |

**Comment by mashanadavis** [comment]
Finally got a chance to review these pages. Here's the outcome:

Page Not Found - 24, 51, 296, 301, 311, 331, 336, 346, 356, 361, 366, 371, 381, 1101 - Did these pages get renamed or deleted? Is there a way to track them down? 

The following have content (they're Guide - Service pages). The node-level menu block is displayed, no redundant links, and the block has a title (Library Services). 
  45	 	sidebar_first 	 	
321 	sidebar_first
326 	sidebar_first
341 	sidebar_first
376 	sidebar_first
386 	sidebar_first

When you ask about redundancy, what do you mean? Are the links redundant to what? The global navigation? 

Brian has some ideas about the node-level menu block and the global navigation under Services. He thought the fly out could go away (don't expand the menu), and just have the service name display. He can expound on this.

**Comment by mashanadavis** [comment]
Ted - Can you confirm that ticket is still in play? My comments are above.

**Comment by tgifford-webfirst** [comment]
## Status

There is a bug in the node_level_blocks module where it does not delete old settings once the node is deleted: https://www.drupal.org/node/2704889. For the time being I've cleaned out the old node settings.

### Nodes with node-level blocks

| nid  | region | redundant* &nbsp; |  on desired pages&nbsp; | has title |
|------|---------|--------------|-----------------------|-----------|
|   45 &nbsp; | sidebar_first &nbsp;  |N/A<sup>1</sup>|Y|N|
|  161 &nbsp; | content      &nbsp;  |N |*N* |Y |
|  326 &nbsp; | sidebar_first &nbsp; |Y<sup>2</sup>|Y?|N|

\* redundant means a similar link appears in the main menu (global or secondary navigation) and the node-level block.

Notes:
1. Node 45 should perhaps have secondary navigation from the main menu.
1. The 3D printing links are related, though not identical.

## Next Steps
* Decide whether we need this module, since it is only used three places at present.
* If we are keeping it, address the two notes above.

**Comment by mashanadavis** [comment]
We do not need this module.

**Comment by tgifford-webfirst** [comment]
Very good, I will disable and uninstall the module.
