### ISSUE TITLE
Performance: Consider removing special_menu_items module

### ISSUE THREAD

**Issue by tgifford-webfirst** [NIHL/Drupal7-Migration#73]
[Special Menu Items](http://www.drupal.org/project/special_menu_items) provides a better administrator experience by allowing <nolink>, etc., to be entered as a path in menu items. However, it implements THEME_link() to replace the rendered link with another tag, which may be causing a noticeable performance issue. See https://api.drupal.org/api/drupal/includes!common.inc/function/l/7.

Approaches

1. Disable the special_menu_items_link() theme function
  a. Disable the special_menu_items module, or
  b. Implement hook_implements_alter(). 
  c. Set the 'theme_link' variable to FALSE.

2. Restore the functionality
  a. Patch the l() function, or
  b. Implement THEME_menu_link(), which will only affect menu links (for a single menu, if desired) and have a lower overhead than THEME_link().

My gut says keep the module enabled to help the administrators out, but disable the theme function and implement THEME_menu_link(), i.e. Approaches 1.c and 2.b.

**Comment by tgifford-webfirst** [comment]
It works well to set theme_link to false--we don't even need to implement a new THEME_menu_link(), at least not at this point. I added help text to the menu add/edit link form in case an administrator gets curious in the future.

**Comment by mashanadavis** [comment]
Ted - Is this related to your suggestion to use a three menu approach---one menu for each customer group (CMS, HHS, NIH)?

**Comment by tgifford-webfirst** [comment]
No, this is not related to the three-menu approach. The special menu items are the 2nd-level headings in the global navigation, i.e. Requests, Library Services, and Facilities under the Services section. They are stored as menu items in Drupal, but there is no corresponding page. These special menu items are also rendered in the secondary menu as headings.

This ticket was about the (negative) performance of the contributed module that supports this functionality. Fortunately, we were able to work around the specific issue with the module, while still using it for the remaining functionality.
