### ISSUE TITLE
Instruction: Add "Reset or Clear All" button to facets

### ISSUE THREAD

**Issue by mashanadavis** [NIHL/Drupal7-Migration#77]
Feedback from instructors: Filtering options need a way to be cleared or adjusted to “all” otherwise, as users start selecting filtering options they cannot undo.

**Comment by mashanadavis** [comment]
Using checkboxes for the facets instead of multi-select drop downs may help with this. 

The NIH Subjects facet was also suggested to be removed as it didn't appear to be of much use to the users (again based on feedback from the instructors). This facet has the most options and a checkbox wouldn't be useful here. But, the other entries may be fine.

**Comment by tgifford-webfirst** [comment]
The better_exposed_filters module is likely part of the solution here.

**Comment by tgifford-webfirst** [comment]
The training calendar and listing views are currently set up as Web Page nodes with a view reference field. This creates several issues with the paging (prev/next month) and default reset button provided by views. I could document these issues in separate tickets, but I think the better approach is to use views the way it works best: as a non-ajax page. We can still add the introductory text above the view, but it would not be node content (at least in the simplest implementation), it would be a views header text block.

This approach does have the drawback of not showing up in the site-wide search. If someone searched for "training session calendar", for example, we might want them to see a link to the calendar, but that wouldn't happen in the simplest implementation. 

A more complex (fragile, maintenance-intensive?) implementation would retain the Web Page node with its searchable content, but any attempts to access that page would be redirected to the view, which would then embed the node content in the header.

Another alpha-quality option would be to use https://www.drupal.org/project/apachesolr_nan to index the view for site-wide search. As an alpha release, we may run into issues there.

The other consideration is whether any of the other fields or settings available on a Web Page (such as NIH Subjects, Customer Group, etc.) need to be emulated with the views approach.

All that being said, I recommend the simple views approach, but I don't know the whole history here. Thoughts?

**Comment by mashanadavis** [comment]
OK, now that my head has stopped spinning from all of the options, let me try to explain what we want to happen here. We assumed that the calendar and list views were actual Views, which yes would be the simplest implementation. Classes should be viewable in a calendar or list View. The classes themselves should be searchable, not the View itself. I don’t think that anyone would search for the calendar or a list of classes if I understand the recommended option correctly. When you say “do the other elements of a webpage need to be emulated in the views…” can you elaborate?

**Comment by cmndr-king** [comment]
At what point would it be easier to replace this imperfect module with something else?

**Comment by svpatel1** [comment]
Issue example: Search  'reference management'  first link is a link to all classes (calender).

**Comment by tgifford-webfirst** [comment]
Consensus is to implement this as a view page (instead of a node with a view reference). We can index the intro text for the site-wide search in the future if necessary.
