### ISSUE TITLE
Remove numbers after taxonomy entries

### ISSUE THREAD

**Issue by mashanadavis** [NIHL/Drupal7-Migration#80]
I believe these numbers are the actual node ID, but I could be wrong. Either way, they need to removed as they can be confusing to content editors. Looking at the facets on various search pages, the number doesn't display to the users.

**Comment by tgifford-webfirst** [comment]
Which pages does this apply to? I think these are probably the numbers of items that would be shown if the facet was clicked.

**Comment by mashanadavis** [comment]
The feedback was referring to when you’re logged in as an Admin. The number doesn’t appear after a term to the user. On the facet, yes, that number refers to the number of results related to that term.

**Comment by tgifford-webfirst** [comment]
Various field widgets from Drupal core and contrib modules include the referenced entity id in parentheses or brackets. This allows referring to nodes with the same title, but different node IDs, for example. The content editors can be trained to ignore the number, or pay attention to it when it matters.
