### ISSUE TITLE
Instruction: Restrict Instructor role to Training Session and Online Tutorials content types

### ISSUE THREAD

**Issue by mashanadavis** [NIHL/Drupal7-Migration#81]
Feedback from instructors: Trainers should only be able to create training sessions and online tutorials, not Training (parent). 

Also, restrict adding a new Training (parent) in the Training Session content type. This may not be possible.

**Comment by tgifford-webfirst** [comment]
Are you referring to users with the "Instruction Lead" role, or is this a new role?

**Comment by mashanadavis** [comment]
Everyone on staff will have permission to add content to the site and may have multiple roles. So, let us review the roles.

**Comment by mashanadavis** [comment]
The following roles are being reviewed:

Admin/Super User

Content Author - consists of ERM Librarians, HHS Librarians, Instructors, Service Area leads. I do not believe we will make sub-roles, rather assign this role to all staff.

Approver - this role would only be useful if/when a workflow is implemented for the site. Can a workflow be implemented for parts of the site; for example, only the homepage?

**Comment by mashanadavis** [comment]
There is a workflow for training sessions, so we don't need to add a role or permissions to restrict these content types. Workflow is not turned on for the training and online tutorial content types. Maybe we can implement a rule that only the Instruction Team leads create content for these two content types.

For now, we will not have a separate roles.
