### ISSUE TITLE
Instruction: Supplemental materials pop up not working in Chrome

### ISSUE THREAD

**Issue by mashanadavis** [NIHL/Drupal7-Migration#83]
Supplemental material function/window not displaying in Chrome when attempting to add documents to session information.

**Comment by tgifford-webfirst** [comment]
It displays for me when logged in as a site administrator, with Chrome (version 47.0.2526.111 m). I am seeing some javascript errors, but the supplemental material windows apears. This is for a new session--are you editing an existing session with existing supplemental materials? Can you provide a complete test case?

**Comment by mashanadavis** [comment]
MaShana will test two scenarios: creating a new class and editing an existing class.

**Comment by mashanadavis** [comment]
I tried to update an existing class and got an error on the file type. The allowable types are .pdf and .ppt. We need to extend this list, and also the version of MS Office documents. I tried to upload a 2013 PPT with the extension .pptx. I looked under Structure > File Type (http://nihlibrarystg.prod.acquia-sites.com/admin/structure/file-types/add), but didn’t see the file types to add.

**Comment by tgifford-webfirst** [comment]
The default list of Document types is restricted by a field setting for Supplemental Materials. See http://nihlibrarystg.prod.acquia-sites.com/admin/structure/types/manage/training/fields/field_supplemental_materials. I added pptx, so this should be fixed.

**Comment by mashanadavis** [comment]
Thanks Ted. I updated the file types and also added video, images, etc. to files that can be uploaded.

**Comment by mashanadavis** [comment]
I was able to add a file to an existing class.
