### ISSUE TITLE
Index Views pages in Solr for site-wide search

### ISSUE THREAD

**Issue by tgifford-webfirst** [NIHL/Drupal7-Migration#86]
The introductory text on e.g. the training calendar is not indexed in Solr because it is part of the view, not a node.

**Comment by tgifford-webfirst** [comment]
From #77: 

A more complex (fragile, maintenance-intensive?) implementation would retain the Web Page node with its searchable content, but any attempts to access that page would be redirected to the view, which would then embed the node content in the header.

Another alpha-quality option would be to use https://www.drupal.org/project/apachesolr_nan to index the view for site-wide search. As an alpha release, we may run into issues there.

**Comment by tgifford-webfirst** [comment]
I've implemented the approach in the first paragraph, namely keeping the nodes around, but redirecting any attempts to access them to the view.

**Comment by tgifford-webfirst** [comment]
Test this by searching for words in the introductory text in the sitewide search, and see if you get redirected to the right place.

**Comment by mashanadavis** [comment]
Conducted a search on "work related skills" and the top two results were the Training & Events page. Is this the desired functionality or fix?

**Comment by tgifford-webfirst** [comment]
This is the desired functionality, mostly. The remaining question is whether you want to have different introductory/searchable content for the calendar vs list view. I recommend keeping it simple and showing the same text for each page; in that case, only one search result would show up.

**Comment by tgifford-webfirst** [comment]
Decided to have a single node (same intro text). Will redirect to Training Calendar.

**Comment by tgifford-webfirst** [comment]
Removed redundant node and created redirects.
