### ISSUE TITLE
Error: TB Menus

### ISSUE THREAD

**Issue by mashanadavis** [NIHL/Drupal7-Migration#87]
The website is generating an error related to TB Menus. I added sub-pages to the service area pages (aka as Guides - Services) and then the error started appearing.

The error appears across the site, not on a specific pages. Here are the errors.

Notice: Undefined offset: 0 in tb_megamenu_insert_tb_item() (line 343 of /mnt/www/html/nihlibrarystg/docroot/sites/all/modules/tb_megamenu/tb_megamenu.functions.inc).

Notice: Undefined offset: 0 in tb_megamenu_insert_tb_item() (line 343 of /mnt/www/html/nihlibrarystg/docroot/sites/all/modules/tb_megamenu/tb_megamenu.functions.inc).

Notice: Undefined offset: 0 in tb_megamenu_insert_tb_item() (line 343 of /mnt/www/html/nihlibrarystg/docroot/sites/all/modules/tb_megamenu/tb_megamenu.functions.inc).

I also noticed that under Services > Library Services > 3D Printing, that three of the sub-pages do not appear in the global navigation but do appear as menu options under the nested menu on the actual service page: http://nihlibrarystg.prod.acquia-sites.com/node/321. Might be a separate ticket, but assumed it was related.

**Comment by tgifford-webfirst** [comment]
This is a bug in tb_megamenu. The issue can be resolved be re-saving the tb_megamenu config, but there is also a candidate patch available on the d.o issue: https://www.drupal.org/node/2482491. I will apply the patch for the time being.

**Comment by tgifford-webfirst** [comment]
This same function is responsible for the erroneous re-ordering of menu items. I'll create another ticket for that.

**Comment by mashanadavis** [comment]
Do we need to reconsider using another meningitis module? I cringe at even suggesting it.


-------- Original message --------

**Comment by tgifford-webfirst** [comment]
Let's defer the ticket on the ordering of menu items. If we run into another issue in the meantime, it may be worth looking at the Superfish module or other alternatives.





On Wed, Mar 16, 2016 at 4:31 PM -0700, "MaShana Davis" <notifications@github.com> wrote:










Do we need to reconsider using another meningitis module? I cringe at even suggesting it.





-------- Original message --------

**Comment by tgifford-webfirst** [comment]
For the record, the only strong alternatives are:
* https://www.drupal.org/project/megamenu
* https://www.drupal.org/project/superfish
* Rolling our own.
