### ISSUE TITLE
Clarify non-NIH access

### ISSUE THREAD

**Issue by cmndr-king** [NIHL/Drupal7-Migration#89]
Add description into the authentication workflow to make it clear that we're not able to offer accounts for employees or contractors who are not directly connected to NIH or HHS.

**Comment by mashanadavis** [comment]
Brian suggested using a simple statement, like:

"Remote access to the NIH Library is available to NIH staff and subscribing HHS agencies."

**Comment by cmndr-king** [comment]
I'd prefer "Remote access to the NIH Library is only available to NIH staff and subscribing HHS agencies."

**Comment by theBrarian** [comment]
Sounds fine to me.

**Comment by mashanadavis** [comment]
As of March 30, James is going to update the Login page layout document on Basecamp (https://asset1.basecamp.com/2765815/projects/7275781/attachments/218456084/HHS%20DL%20authentication%20page-v2-20160322.docx) with this language and close this ticket. Going forward we will focus efforts on Ticket #70.

**Comment by mashanadavis** [comment]
James - Can we close this ticket?

**Comment by cmndr-king** [comment]
yes
