### ISSUE TITLE
Redirect previously-authenticated users to their last login page

### ISSUE THREAD

**Issue by tgifford-webfirst** [NIHL/Drupal7-Migration#91]
This could be done with a cookie, set to expire after a proposed 90 days. 

The cookie can not be set after authentication has succeeded because the user will be accessing the site from EzProxy, not at the original URL.

We will need to set the cookie via javascript before sending them to the EzProxy or SSO authentication, or during a redirect.

**Comment by tgifford-webfirst** [comment]
Now that we have direct links to the SSO pages in the megamenu, do we really need to add the cookie? The only users that would require more than one click are IHS users, or users that can't use the dropdown for some reason.

If you still want the cookie, is this still a priority?

**Comment by 4benhope** [comment]
Agree we can drop the cookie now that we’ve streamlined the process.


-James
_______________________________
James King, MLS, FSLA
(301) 496-2187

http://about.me/cmndr_king

**Comment by tgifford-webfirst** [comment]
Moved to review, we can close it at the next meeting, or sooner.
