### ISSUE TITLE
Harmonize content for login pages

### ISSUE THREAD

**Issue by tgifford-webfirst** [NIHL/Drupal7-Migration#93]
This includes warnings regarding Active Directory issues, help text, logos, etc.

**Comment by tgifford-webfirst** [comment]
Based on the basecamp discussion, there aren't any pages to harmonize (only the main login page and the IHS page)

**Comment by mashanadavis** [comment]
Are we in agreement with Ted's assessment? Does the page layout require updating/formatting? If so, then maybe start a new ticket. 

Otherwise this might be a done deal.

**Comment by cmndr-king** [comment]
correct, with the revisions in the latest document, we've eliminated a layer.  I will close the ticket.
