### ISSUE TITLE
TB Megamenu doesn't sort menu links alphabetically

### ISSUE THREAD

**Issue by tgifford-webfirst** [NIHL/Drupal7-Migration#96]
Drupal core and most contrib modules sort menu links alphabetically by default. TB megamenu does not.

**Comment by mashanadavis** [comment]
So knowing this, do we reorder the links ourselves? I want to make note of this when I provide training for our content authors.

**Comment by tgifford-webfirst** [comment]
I patched the module, so it shouldn't be necessary to order links manually if you want them sorted alphabetically.
