### ISSUE TITLE
PHP Error - View Training Session in Admin

### ISSUE THREAD

**Issue by svpatel1** [NIHL/Drupal7-Migration#98]
http://nihlibrarystg.prod.acquia-sites.com/content/cancer-genome-atlas-tcga-data-analysis
(logged in as an admin)

    Notice: Undefined index: reverse_field_wos_subject_node in views_handler_field_field->get_base_table() (line 149 of /mnt/www/html/nihlibrarystg/docroot/sites/all/modules/views/modules/field/views_handler_field_field.inc).
    Notice: Undefined index: in views_handler_field_field->access() (line 127 of /mnt/www/html/nihlibrarystg/docroot/sites/all/modules/views/modules/field/views_handler_field_field.inc).
    Notice: Undefined index: reverse_field_wos_subject_node in views_handler_field_field->get_base_table() (line 149 of /mnt/www/html/nihlibrarystg/docroot/sites/all/modules/views/modules/field/views_handler_field_field.inc).
    Notice: Undefined index: in views_handler_field_field->query() (line 186 of /mnt/www/html/nihlibrarystg/docroot/sites/all/modules/views/modules/field/views_handler_field_field.inc).
    Notice: Undefined index: entity keys in views_handler_field_field->query() (line 198 of /mnt/www/html/nihlibrarystg/docroot/sites/all/modules/views/modules/field/views_handler_field_field.inc).

**Comment by tgifford-webfirst** [comment]
This was coming from the Related Topic Guides block in the latest_guides view (block_3). There was a broken handler for a relationship. Recreating the relationships and contextual filters for that display fixed the issue.
