### ISSUE TITLE
Add agency authentication links to Login megamenu

### ISSUE THREAD

**Issue by tgifford-webfirst** [NIHL/Drupal7-Migration#99]

**Comment by mashanadavis** [comment]
Links added and linking to the correct login page(s). 

James, do you want to test this or are you satisfied with the functionality?

**Comment by cmndr-king** [comment]
Works for me, I closed the ticket.


-James
_______________________________
James King, MLS, FSLA
(301) 496-2187

http://about.me/cmndr_king
